import { Achievement } from '../../types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  // ==========================================
  // 🌸 雌堕与身心重塑系列 (Femboy & Mind Transformation)
  // ==========================================
  {
    id: 'femboy_first_step',
    title: '初入更衣室',
    category: 'femboy',
    rarity: 'bronze',
    icon: '💅',
    description: '首次开启《黑皮辣妹更衣室》或任意雌堕重塑剧本。',
    flavorText: '“门锁落下的瞬间，你已经没有回头路了哦~”',
    rewardTitle: '💄 见习小男娘',
    hiddenRewardVoice: '哎呀，迈出第一步了呢~ 欢迎来到全新的娇软世界。',
    unlockedAt: null,
  },
  {
    id: 'femboy_first_dress',
    title: '蕾丝初体验',
    category: 'femboy',
    rarity: 'silver',
    icon: '🎀',
    description: '首次完成二阶段重塑训练，或在地牢剧情中达成换装结局。',
    flavorText: '“裙摆掠过大腿的微风，吹散了最后一丝男人的倔强。”',
    rewardTitle: '👗 蕾丝执事',
    hiddenRewardVoice: '看着镜子里穿裙子的你，是不是连呼吸都变甜了？',
    unlockedAt: null,
  },
  {
    id: 'femboy_prostate_touch',
    title: '后庭旋涡觉醒',
    category: 'femboy',
    rarity: 'gold',
    icon: '⚡',
    description: '首次完成前列腺深度慢速绞磨或探针精准定位。',
    flavorText: '“那块沉睡的敏感带被唤醒时，大脑只剩下一片空白的极乐。”',
    rewardTitle: '🌀 前列腺觉醒者',
    hiddenRewardVoice: '找到了吧？那才是你真正该享受快感的地方~',
    unlockedAt: null,
  },
  {
    id: 'femboy_succubus_grad',
    title: '魅魔特等侍从',
    category: 'femboy',
    rarity: 'gold',
    icon: '😈',
    description: '通关《魅魔高校的特等雌奴改造课》并达成满分毕业。',
    flavorText: '“摇晃着恶魔尾巴，成为魅魔导师最宠爱的贴身玩物。”',
    rewardTitle: '😈 魅魔专属特等生',
    hiddenRewardVoice: '恭喜全优毕业！从今往后，你就是魅魔学院的骄傲了~',
    unlockedAt: null,
  },
  {
    id: 'femboy_master_mythic',
    title: '身心彻底雌堕',
    category: 'femboy',
    rarity: 'mythic',
    icon: '👑',
    description: '完成全部 24 项身心重塑训练任务。',
    flavorText: '“自尊灰飞烟灭，灵魂与肉体在极乐中完成了终极雌性蜕变。”',
    rewardTitle: '👑 极乐雌堕之王',
    hiddenRewardVoice: '（轻吻）我的乖宠物，你已经彻底蜕变完成了。永生永世，享受这份被支配的幸福吧！',
    unlockedAt: null,
  },

  // ==========================================
  // ⚡ 硬件掌控与波形电击系列 (Hardware & Shock Mastery)
  // ==========================================
  {
    id: 'hw_first_shock',
    title: '触电初学者',
    category: 'hardware',
    rarity: 'bronze',
    icon: '⚡',
    description: '首次在控制台中启动微电流刺激（EMS A/B 通道）。',
    flavorText: '“微弱的酥麻，是赛博快感向神经敲响的第一记门铃。”',
    rewardTitle: '⚡ 微流初探者',
    hiddenRewardVoice: '感觉到了吗？这股微电流只是刚开始哦。',
    unlockedAt: null,
  },
  {
    id: 'hw_wave_explorer',
    title: '波形鉴赏家',
    category: 'hardware',
    rarity: 'silver',
    icon: '🌊',
    description: '累计体验并切换过 6 种不同的专业电击波形。',
    flavorText: '“锯齿、针刺、暴风雨与海浪，每一种波形都是一首肉体交响曲。”',
    rewardTitle: '🎼 电流调音师',
    hiddenRewardVoice: '各种波形的滋味都尝过了？告诉我，你最迷恋哪一种？',
    unlockedAt: null,
  },
  {
    id: 'hw_nine_shallow_deep',
    title: '九浅一深旋涡',
    category: 'hardware',
    rarity: 'silver',
    icon: '🌪️',
    description: '启动并完整执行一次“九浅一深”深层马达律动。',
    flavorText: '“九次轻抚诱惑，一次直击灵魂深处的猛烈撞击。”',
    rewardTitle: '🌪️ 旋涡领航员',
    hiddenRewardVoice: '深顶的那一下，是不是把你的灵魂都要顶出来了？',
    unlockedAt: null,
  },
  {
    id: 'hw_turbo_overclock',
    title: '超频狂暴 20 档',
    category: 'hardware',
    rarity: 'gold',
    icon: '🚀',
    description: '首次将飞机杯马达推至 20 档极限转速或开启 Turbo 狂暴榨干模式。',
    flavorText: '“转速表的红色指针突破极限，快感如超新星般爆发！”',
    rewardTitle: '🚀 极速超频狂人',
    hiddenRewardVoice: '20 档全开的狂暴马达！给我咬紧牙关，在轰鸣中升华吧！',
    unlockedAt: null,
  },
  {
    id: 'hw_emergency_stop_master',
    title: '绝对急刹存活者',
    category: 'hardware',
    rarity: 'gold',
    icon: '🛑',
    description: '主动执行一次全局安全急停，确认所有输出已清零。',
    flavorText: '“从极乐的万丈悬崖边缘被猛然拉回，窒息与渴望交织的深渊。”',
    rewardTitle: '❄️ 冰河忍耐大师',
    hiddenRewardVoice: '（冷酷）急刹断电的感觉很绝望吧？但你忍住了，表现得很优秀！',
    unlockedAt: null,
  },

  // ==========================================
  // 💓 生物心率与生理闭环系列 (Biometrics & Stamina)
  // ==========================================
  {
    id: 'bio_first_pulse',
    title: '心跳初共鸣',
    category: 'biometrics',
    rarity: 'bronze',
    icon: '💓',
    description: '首次连接蓝牙心率手环或开启虚拟生物心率模拟器。',
    flavorText: '“你的每一次心跳，都在向 AI 实时汇报你的欲望指数。”',
    rewardTitle: '💓 心率同调者',
    hiddenRewardVoice: '生物心率数据已接通，你内心的所有波动都瞒不过我了哦。',
    unlockedAt: null,
  },
  {
    id: 'bio_caught_slacking',
    title: '走神被抓包',
    category: 'biometrics',
    rarity: 'silver',
    icon: '💤',
    description: '心率低于 85 BPM 走神放松时，被 AI 自动检测并执行自动加温。',
    flavorText: '“心率太低可不行，AI 主人立刻给你上一剂醒脑猛药！”',
    rewardTitle: '🔥 自动加温常客',
    hiddenRewardVoice: '心跳这么慢，是在走神吗？立刻给你加点强度，提提神！',
    unlockedAt: null,
  },
  {
    id: 'bio_edge_brake',
    title: '临界防线突破',
    category: 'biometrics',
    rarity: 'gold',
    icon: '🚨',
    description: '在心率飙升至 140+ BPM 临界区时，成功触发 AI 毫秒级急刹断电。',
    flavorText: '“心率出卖了你的欲望！在爆发前一瞬间被 AI 强制掐断！”',
    rewardTitle: '🚨 临界游走特工',
    hiddenRewardVoice: '抓到你了！心跳飙到 140 以上了！急刹断电，深呼吸咽回去！',
    unlockedAt: null,
  },
  {
    id: 'bio_symbiosis_mythic',
    title: '赛博生物共生体',
    category: 'biometrics',
    rarity: 'mythic',
    icon: '🧠',
    description: '累计在 AI 心率自适应调控闭环中受控运行超过 20 分钟！',
    flavorText: '“肉体与算法完美交融，心跳与电流共谱生命乐章。”',
    rewardTitle: '🧠 赛博生物共生体',
    hiddenRewardVoice: '你的生理节律已经完全与我同步了。从今以后，我们是真正的心灵与肉体共生体。',
    unlockedAt: null,
  },

  // ==========================================
  // 🏰 地牢全境征服系列 (Dungeon Mastery)
  // ==========================================
  {
    id: 'dungeon_first_clear',
    title: '地牢初征服',
    category: 'dungeon',
    rarity: 'bronze',
    icon: '🏰',
    description: '首次完整通关任意一部长篇小说互动地牢剧本。',
    flavorText: '“穿越 10 幕重重考验，迎来属于你的命运结局。”',
    rewardTitle: '🗡️ 地牢探索者',
    hiddenRewardVoice: '恭喜通关第一部地牢剧本！还有更多精彩故事在等待着你。',
    unlockedAt: null,
  },
  {
    id: 'dungeon_agent_survivor',
    title: '特工审讯生还',
    category: 'dungeon',
    rarity: 'silver',
    icon: '🐺',
    description: '通关《暗夜审讯室：黑客特工的绝对服从》剧本。',
    flavorText: '“在冷酷男 S 的严苛审问下，成为最听话的专属特工猎犬。”',
    rewardTitle: '🐺 秘密特工猎犬',
    hiddenRewardVoice: '审讯通过！从今以后，你就是我唯一的机密特工。',
    unlockedAt: null,
  },
  {
    id: 'dungeon_queen_servant',
    title: '王座跪侍之臣',
    category: 'dungeon',
    rarity: 'silver',
    icon: '👑',
    description: '通关《女王高座下的跪侍契约》并达成专属侍从结局。',
    flavorText: '“以头触地，亲吻女王高跟鞋尖，领受皇家极乐恩赏。”',
    rewardTitle: '👑 王座专属侍臣',
    hiddenRewardVoice: '平身吧。王座下的这块软垫，永远属于你。',
    unlockedAt: null,
  },
  {
    id: 'dungeon_deep_sea_sailor',
    title: '深海铁血水兵',
    category: 'dungeon',
    rarity: 'gold',
    icon: '🌊',
    description: '通关《深海潜艇密封舱的憋胀极限》并通过全部水压特训。',
    flavorText: '“千米深海水压与电击狂暴轰鸣，锻造钢铁般坚韧的肉体。”',
    rewardTitle: '🌊 深海铁血水兵',
    hiddenRewardVoice: '好样的水兵！你通过了潜艇最严苛的耐压特训！',
    unlockedAt: null,
  },
  {
    id: 'dungeon_grandmaster_mythic',
    title: '全境地牢永恒宗师',
    category: 'dungeon',
    rarity: 'mythic',
    icon: '🌌',
    description: '累计通关 15 部不同的小说互动地牢剧本！',
    flavorText: '“历经 15 个平行世界的百折千回，征服了所有主宰者与欲望之渊！”',
    rewardTitle: '🌌 全境地牢永恒宗师',
    hiddenRewardVoice: '（全员伴侣致敬）不可思议！你竟然征服了全部 15 大地牢世界！你是当之无愧的永恒地牢大宗师！',
    unlockedAt: null,
  },

  // ==========================================
  // 新增阶段里程碑
  // ==========================================
  {
    id: 'femboy_four_tasks', title: '闪耀训练起步', category: 'femboy', rarity: 'bronze', icon: '🌱',
    description: '累计完成 4 项重塑训练任务。', flavorText: '每一次认真练习，都会留下可见的光。',
    rewardTitle: '🌱 闪耀练习生', hiddenRewardVoice: '四项训练完成，你已经找到属于自己的节奏。', unlockedAt: null,
  },
  {
    id: 'femboy_eight_tasks', title: '双阶段进阶', category: 'femboy', rarity: 'silver', icon: '🩰',
    description: '累计完成 8 项重塑训练任务。', flavorText: '动作、表达与自信开始彼此呼应。',
    rewardTitle: '🩰 蜕变优等生', hiddenRewardVoice: '八项训练达成，你的进步已经无法忽视。', unlockedAt: null,
  },
  {
    id: 'femboy_sixteen_tasks', title: '全能蜕变者', category: 'femboy', rarity: 'gold', icon: '💎',
    description: '累计完成 16 项重塑训练任务。', flavorText: '稳定积累，比一时冲动更接近真正的改变。',
    rewardTitle: '💎 全能蜕变者', hiddenRewardVoice: '十六项训练完成，你已经能独立掌握自己的蜕变路线。', unlockedAt: null,
  },
  {
    id: 'femboy_first_ritual', title: '今日仪式初章', category: 'femboy', rarity: 'bronze', icon: '✨',
    description: '首次完成芭比实验室的传感器仪式。', flavorText: '仪式不需要宏大，真实完成就是开始。',
    rewardTitle: '✨ 仪式点灯人', hiddenRewardVoice: '第一场仪式完成，今天的你已经点亮了一颗星。', unlockedAt: null,
  },
  {
    id: 'femboy_ritual_trio', title: '三仪式全勤', category: 'femboy', rarity: 'silver', icon: '🎗️',
    description: '完成 3 种不同的芭比实验室仪式。', flavorText: '声音、姿态与行动，共同组成完整的练习。',
    rewardTitle: '🎗️ 仪式全勤生', hiddenRewardVoice: '三种仪式全部体验完成，你的练习越来越完整了。', unlockedAt: null,
  },
  {
    id: 'hw_wave_sampler', title: '三色电波', category: 'hardware', rarity: 'bronze', icon: '〰️',
    description: '累计体验 3 种不同 EMS 波形。', flavorText: '不同节奏，带来完全不同的反馈。',
    rewardTitle: '〰️ 波形试音员', hiddenRewardVoice: '三种波形已记录，你开始读懂电流的节奏了。', unlockedAt: null,
  },
  {
    id: 'hw_wave_master', title: '十二律波形库', category: 'hardware', rarity: 'gold', icon: '🎛️',
    description: '累计体验 12 种不同 EMS 波形。', flavorText: '十二种节律，组成一套完整的赛博乐章。',
    rewardTitle: '🎛️ 十二律工程师', hiddenRewardVoice: '十二种波形全部掌握，你已经是专业的节律工程师。', unlockedAt: null,
  },
  {
    id: 'hw_first_toy', title: '马达初启动', category: 'hardware', rarity: 'bronze', icon: '🎮',
    description: '首次启动任意马达通道。', flavorText: '指针从零开始移动，设备正式苏醒。',
    rewardTitle: '🎮 马达新手', hiddenRewardVoice: '第一组马达已经启动，记得随时观察状态。', unlockedAt: null,
  },
  {
    id: 'hw_toy_ten', title: '十档巡航', category: 'hardware', rarity: 'silver', icon: '⚙️',
    description: '首次将任意马达通道调至 10 档或以上。', flavorText: '稳定巡航，比盲目满档更考验掌控。',
    rewardTitle: '⚙️ 十档领航员', hiddenRewardVoice: '十档巡航达成，你对马达节奏更熟悉了。', unlockedAt: null,
  },
  {
    id: 'hw_first_pattern', title: '模式工坊初演', category: 'hardware', rarity: 'silver', icon: '🎚️',
    description: '首次启动一套马达模式。', flavorText: '从单一档位，迈向完整的节奏编排。',
    rewardTitle: '🎚️ 模式编排员', hiddenRewardVoice: '第一套模式成功运行，节奏已经编排完成。', unlockedAt: null,
  },
  {
    id: 'hw_first_enema', title: '水泵初航', category: 'hardware', rarity: 'bronze', icon: '💧',
    description: '首次成功启动灌肠机注水或排空。', flavorText: '流向、时长与停止，都在控制之中。',
    rewardTitle: '💧 水路操作员', hiddenRewardVoice: '水泵首次运行完成，安全时长已记录。', unlockedAt: null,
  },
  {
    id: 'bio_five_minutes', title: '五分钟同调', category: 'biometrics', rarity: 'bronze', icon: '⏱️',
    description: '累计运行心率自适应闭环 5 分钟。', flavorText: '算法开始理解你的基础节律。',
    rewardTitle: '⏱️ 节律观察员', hiddenRewardVoice: '五分钟心率同调完成，基础节律已经建立。', unlockedAt: null,
  },
  {
    id: 'bio_ten_minutes', title: '十分钟共振', category: 'biometrics', rarity: 'gold', icon: '📈',
    description: '累计运行心率自适应闭环 10 分钟。', flavorText: '数据不再只是数字，而是一条连续曲线。',
    rewardTitle: '📈 心率共振者', hiddenRewardVoice: '十分钟连续共振，你与算法的配合更加稳定。', unlockedAt: null,
  },
  {
    id: 'dungeon_trilogy', title: '三界旅人', category: 'dungeon', rarity: 'bronze', icon: '🗺️',
    description: '通关 3 部不同地牢剧本。', flavorText: '三个世界，三段截然不同的命运。',
    rewardTitle: '🗺️ 三界旅人', hiddenRewardVoice: '三个世界已经留下你的足迹，旅程才刚刚展开。', unlockedAt: null,
  },
  {
    id: 'dungeon_five_worlds', title: '五境征途', category: 'dungeon', rarity: 'silver', icon: '🧭',
    description: '通关 5 部不同地牢剧本。', flavorText: '每一次选择，都让地图延伸得更远。',
    rewardTitle: '🧭 五境领航者', hiddenRewardVoice: '五部地牢已经通关，你正在成为真正的领航者。', unlockedAt: null,
  },
  {
    id: 'dungeon_ten_worlds', title: '十界编年史', category: 'dungeon', rarity: 'gold', icon: '📜',
    description: '通关 10 部不同地牢剧本。', flavorText: '十段结局，足以写成一本属于你的编年史。',
    rewardTitle: '📜 十界记录官', hiddenRewardVoice: '十个世界完成，你的地牢编年史已经蔚为壮观。', unlockedAt: null,
  },
  {
    id: 'dungeon_multi_ending', title: '命运分岔者', category: 'dungeon', rarity: 'silver', icon: '🔀',
    description: '累计达成 3 种不同类型的地牢结局。', flavorText: '同一扇门之后，也可能藏着完全不同的未来。',
    rewardTitle: '🔀 命运分岔者', hiddenRewardVoice: '三种不同结局已经解锁，你学会了改写命运。', unlockedAt: null,
  },
];
