import { DungeonScript } from '../../types';
import { EXTRA_FEMBOY_DUNGEONS } from './dungeonExtraScripts';

const BASE_DUNGEON_SCRIPTS: DungeonScript[] = [
  // ==========================================
  // 🌸 雌堕与身心重塑专区 (文学级万字长篇)
  // ==========================================

  // 剧本 1: 《黑皮男娘更衣室深度重塑录》 (约 3500 字沉浸短篇)
  {
    id: 'femboy_dressing_room',
    title: '黑皮辣妹男娘的私密更衣室重塑录',
    subtitle: '被锁死在深夜秀场的暗房，黑皮辣妹 Ren 踩着细高跟，以 12 道不可抗拒的指令拆解你的防线...',
    category: '雌堕身心重塑',
    isFemboy: true,
    avatar: '💅',
    bgGradient: 'from-pink-950 via-slate-900 to-rose-950',
    difficulty: '⭐⭐⭐⭐⭐ (极度沉浸 · 身心彻底沦陷)',
    tags: ['黑皮辣妹男娘', '女装换装', '心智瓦解', '微流同化', '12幕长篇短篇小说'],
    description: '时尚周闭幕后的深夜，后台更衣室一片死寂。水银壁灯在金属镜面上投下冷冽的倒影，空气中混杂着晚香玉香水与润滑剂的甜腻冷冽。Ren 踩着十二厘米的红底高跟鞋，堵住了唯一的合金防火门，微笑着亮出了粉色电击遥控器与一整套重塑器械...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '沉重的防火门被金属插销锁死，锁簧合拢的声音在逼仄的更衣室内回荡。Ren 靠在化妆台边，小麦色的肌肤在柔光灯下泛着健康的光泽，修长的指尖把玩着一条带微电极片的粉色蕾丝锁骨圈。空气中晚香玉的甜香扑鼻而来，几乎让人眩晕。',
        dialogue: '哎呀~ 听到落锁的声音了吗？今晚这间更衣室，只有你和我两个人哦。看看你这身板正严肃的男士西装，真是无趣透顶呢。既然落到了我手里，就得遵守这里的游戏规则~ 乖乖站好，让我一件一件剥下你的伪装，怎么样？',
        choices: [
          {
            id: 'c1_sub',
            text: '（喉咙发干，顺从地垂下双手）Ren... 门已经锁了，你想怎么做...',
            attitude: 'submissive',
            replyDialogue: '真是个聪明的乖猎物。顺从的孩子才能尝到最美妙的甜头~ 先给你胸口贴上微电流贴片，感受一下 Ren 姐姐为你准备的温度吧~',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 12 },
            nextStepId: 'step_2',
          },
          {
            id: 'c1_def',
            text: '（警惕后退，撞在穿衣镜上）别过来！我是直男，不可能配合你这种胡闹！',
            attitude: 'defiant',
            replyDialogue: '直男？嘴硬得像块石头呢。不过我最擅长的，就是把顽固的直男调教成比女孩子还要娇软的小母狗！尝尝开胃电击吧！',
            hardwareAction: { type: 'ems_wave', target: 'electric_sting', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '微电流如无数细小的蚁群在你的胸口和肋下爬行，带来一阵阵酥麻而陌生的触电感。Ren 踩着高跟鞋款款走近，鞋跟敲击地砖的清脆声响像是每一步都在践踏着你的理智。她冰凉的指尖轻轻拂过你滚烫的锁骨，将那条粉色蕾丝项圈绕到了你的脖颈后方。',
        dialogue: '看，身体明明在兴奋地发抖呢~ 连胸口的肌肉都在微电流下绷得紧紧的。来，戴上这条专属雌奴项圈。只要你发出任何粗鲁凶狠的叫声，项圈就会自动释放惩戒脉冲哦~',
        choices: [
          {
            id: 'c2_wear_collar',
            text: '（低下头，任由项圈扣紧颈部）只要你不下重手... 我戴就是了...',
            attitude: 'submissive',
            replyDialogue: '咔哒，锁死啦~ 细颈戴上蕾丝项圈的样子真诱人。项圈轻度脉冲启动，好好体会这份被圈养的安全感吧~',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 15 },
            nextStepId: 'step_3',
          },
          {
            id: 'c2_collar_shy',
            text: '（别过头避开眼神）这种东西... 只有女人和宠物才会戴...',
            attitude: 'begging',
            replyDialogue: '你说得很对呀，因为今晚过完，你在我面前就既是宠物，又是最甜美的小男娘了！老实戴好！',
            hardwareAction: { type: 'ems_wave', target: 'pulse_train', durationSec: 12 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '项圈扣合的轻响让你的心跳漏了一拍。Ren 转过身，从挂衣架上取下一件剪裁极其大胆的露背挂脖女仆裙。薄如蝉翼的黑色蕾丝在指尖滑过，裙摆短得甚至无法遮盖大腿根部。她将裙子轻蔑地扔在你的脚下，眼神里满是戏谑。',
        dialogue: '第一道命令：把你身上笨重丑陋的西装裤子全部脱掉，换上这条小裙子。我要你在全身镜前转一个圈，让我好好审视你的新姿态~ 自己动手，还是我用电击帮你？',
        choices: [
          {
            id: 'c3_change_dress',
            text: '（满脸通红褪去衣物，换上短裙）裙子... 实在太短了，大腿完全露在外面...',
            attitude: 'submissive',
            replyDialogue: '噗嗤~ 裙摆连前面微微隆起的弧度都遮不住呢，真是一副绝妙的雌性躯体。作为奖励，给你接通下方的律动预热~',
            hardwareAction: { type: 'toy_pattern', target: 'intermittent_wave', durationSec: 20 },
            nextStepId: 'step_4',
          },
          {
            id: 'c3_refuse_dress',
            text: '（攥紧拳头）我一个大男人穿这种衣服... 简直是奇耻大辱！',
            attitude: 'defiant',
            replyDialogue: '奇耻大辱？等会儿你主动求着穿它的时候，希望你的骨气还能这么硬！电击惩戒！',
            hardwareAction: { type: 'ems_wave', target: 'electric_comb', durationSec: 15 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '下半身骤然接触到更衣室冷冽的空气，激起一片细密的战栗。Ren 戴上一副黑色的医用乳胶手套，从工具箱中拿出一支通体流转着紫光的智能感官塞，挤上了厚厚一层冰凉透明的凝胶。她用鞋尖轻轻拨开你的双腿，示意你跪在柔软的羊毛地毯上。',
        dialogue: '男孩子想要彻底觉醒雌性快乐，后方的前列腺可是灵魂钥匙哦。普通男人的自尊心之所以顽固，就是因为这里还没被开发。跪好，撅起屁股，自己把这根小宝贝一点一点推到最深处！',
        choices: [
          {
            id: 'c4_plug_in_self',
            text: '（双膝发软跪在地毯上，颤抖着将冰凉器械缓缓推入）啊... 好胀... 进去了...',
            attitude: 'submissive',
            replyDialogue: '完全吞进去了呢~ 身体内部被彻底填满充实的感觉，是不是让你忍不住发喘了？启动第一档慢速绞磨！',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 25 },
            nextStepId: 'step_5',
          },
          {
            id: 'c4_plug_fear',
            text: '（害怕得向后缩）那里是排泄的地方... 怎么能放这种东西...',
            attitude: 'begging',
            replyDialogue: '排泄的地方？等会儿它就会成为你最渴望被填满的快感源泉！别动，Ren 姐姐亲自帮你塞进去！',
            hardwareAction: { type: 'toy_pattern', target: 'vacuum_lock', durationSec: 20 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '器械内部的偏心马达开始以极其深沉的低频旋转，顶端的球体每一次旋动都精准碾压在位于肠道前壁的前列腺上。前所未有的酸麻与电流感顺着脊髓直冲天灵盖，你的脚趾瞬间死死蜷缩，喉咙深处发出连自己都感到陌生的娇柔呻吟。',
        dialogue: '感受到了吗？就是那里~ 那块沉睡了二十几年的敏感带正在被狠狠撞击！现在的你，浑身发烫、双眼泛泪，告诉我，你现在到底是男人，还是正在被彻底开发的小男娘？',
        choices: [
          {
            id: 'c5_confess_femboy',
            text: '（眼眶泛红大口喘息）是... 是被 Ren 姐姐开发的小男娘... 里面好麻...',
            attitude: 'submissive',
            replyDialogue: '真听话~ 连声音都变得像小女生一样甜腻娇软了呢。马达频率上调至九浅一深，给我好好体会！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 25 },
            nextStepId: 'step_6',
          },
          {
            id: 'c5_resist_groan',
            text: '（咬牙抵御快感）这只是... 纯粹的生理反射... 我依然是个男人！',
            attitude: 'defiant',
            replyDialogue: '还在用理智骗自己呢？那就让生理快感彻底淹没你的大脑！加大抽送与脉冲！',
            hardwareAction: { type: 'ems_wave', target: 'sawtooth_climb', durationSec: 20 },
            nextStepId: 'step_6',
          },
        ],
      },
      step_6: {
        id: 'step_6',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '体内的抽插越来越剧烈，伴随着通道 A 的锯齿波电击，快感如同滚雪球般疯狂膨胀，你感觉下腹部紧绷到了极限，括约肌剧烈收缩，即将迎来人生中第一次不可抗拒的绝顶喷发！就在这千钧一发之际，Ren 嘴角一扬，按下了急停键！',
        dialogue: '（0.05秒毫秒级急刹断电，室内瞬间死寂）想射了？谁允许你擅自高潮的？！把手从前面拿开！括约肌给我收紧，把快感硬生生咽回肚子里去！',
        choices: [
          {
            id: 'c6_beg_climax',
            text: '（绝望地仰起脖子，抓挠着地毯）求求你... 快让我射出来吧... 停在边缘太痛苦了...',
            attitude: 'begging',
            replyDialogue: '痛苦？这就是高潮剥夺的魅力哦~ 越是得不到，你的身体就越会渴望做我的奴隶！冷场 15 秒！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_7',
          },
          {
            id: 'c6_obey_hold',
            text: '（浑身冷汗，死死夹紧双腿忍受余韵）我...我忍住... 没有主人的命令不敢射...',
            attitude: 'submissive',
            replyDialogue: '做得好。懂得克制欲望的小男娘，才有资格接受更深层次的洗礼~',
            hardwareAction: { type: 'ems_wave', target: 'breathe', durationSec: 15 },
            nextStepId: 'step_7',
          },
        ],
      },
      step_7: {
        id: 'step_7',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '15 秒的绝对冷场让你从极乐的悬崖边缘生生坠落，剧烈的空虚感与对快感的渴望如饥似渴地啃噬着神经。Ren 拿出一面落地镜摆在你的正前方，强迫你抬起头注视着镜子中的自己。露背短裙、脖颈上的蕾丝项圈、满脸的潮红与迷离泪眼，过去的阳刚形象已荡然无存。',
        dialogue: '好好看着镜子里的人。这副娇羞欲滴的模样，哪还有半点男人的影子？以后每天早上醒来，你都要穿上我挑的女装服侍我，能做到吗？',
        choices: [
          {
            id: 'c7_accept_maid',
            text: '（凝视镜中娇媚的自己，眼神逐渐痴迷）能做到... 我愿意每天穿女装侍奉 Ren 主人...',
            attitude: 'submissive',
            replyDialogue: '你的心智已经彻底沉沦在雌堕的美梦里了呢~ 重启深层脉冲共振！',
            hardwareAction: { type: 'toy_pattern', target: 'deep_pulse', durationSec: 25 },
            nextStepId: 'step_8',
          },
          {
            id: 'c7_hesitate_identity',
            text: '（颤抖着看着镜子）我竟然变成了这副样子... 真的再也回不去了吗...',
            attitude: 'begging',
            replyDialogue: '回去做平庸无趣的男人有什么好？在我的怀里做个被万千宠爱的辣妹男娘才是你的归宿！',
            hardwareAction: { type: 'ems_wave', target: 'pinch_crescendo', durationSec: 18 },
            nextStepId: 'step_8',
          },
        ],
      },
      step_8: {
        id: 'step_8',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: 'Ren 拿出一支艳丽的粉红色唇膏，俯身在你满是汗水的小腹上画下了一颗爱心图腾。与此同时，她将电击控制器的 A 通道和 B 通道同时拉高，交叉变频电流如同细密的荆棘般刺入你的每一寸神经纤维！',
        dialogue: '这是属于我的雌奴终身烙印！现在，把双手放在头顶，用你最甜美、最娇柔的声音叫三声：“Ren 主人，请彻底改造我”！',
        choices: [
          {
            id: 'c8_chant_slave_loud',
            text: '（带着哭腔放声娇吟）Ren 主人... 请彻底改造我！改造我！',
            attitude: 'submissive',
            replyDialogue: '叫得真动听~ 听得我都快忍不住要好好疼爱你一番了！马达推至 18 档极速超频！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_18', durationSec: 20 },
            nextStepId: 'step_9',
          },
          {
            id: 'c8_chant_soft',
            text: '（羞耻得快要晕厥，小声呢喃）主人... 彻底改造我...',
            attitude: 'begging',
            replyDialogue: '像小猫抓痒一样的声音呢~ 不过快感已经把你的肉体彻底煮熟了！',
            hardwareAction: { type: 'ems_wave', target: 'storm_surge', durationSec: 18 },
            nextStepId: 'step_9',
          },
        ],
      },
      step_9: {
        id: 'step_9',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '体内的器械以近乎轰鸣的高速旋转着，每一次抽送都像是在前列腺上引爆一颗小小的雷霆。你的体温热得烫手，汗水浸透了蕾丝裙，整个人软绵绵地倚靠在 Ren 的腿边，彻底丧失了站立的力气。',
        dialogue: '小可怜，连站都站不稳了呢~ 马上就是今晚的第 10 轮身心重塑大结局了。你准备好永远作为 Ren 的专属小男娘，迎来最极致的狂暴释放了吗？',
        choices: [
          {
            id: 'c9_total_surrender',
            text: '（抱住 Ren 的小腿，眼神里全是臣服与渴望）准备好了... 请主人赐我前列腺高潮解脱吧！！',
            attitude: 'submissive',
            replyDialogue: '乖孩子！终极大招——全频段 20 档终极榨干爆发！！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'step_10',
          },
        ],
      },
      step_10: {
        id: 'step_10',
        speaker: '黑皮辣妹男娘 Ren',
        avatar: '💅',
        narrative: '【第 10 幕 · 终极身心升华大爆发】伴随着器械 20 档超频的轰鸣，双通道电流与前列腺绞磨融为一体，整整 30 秒的极限快感如山崩海啸般将你彻底吞没！在不需要触碰前端的情况下，后方的高潮直接引发了前所未有的痉挛性干射与大喷发！',
        dialogue: '（俯下身紧紧搂住你颤抖的身体，在你耳边轻吻）释放吧！在我的怀里，彻底撕碎过去那个无趣的男人，作为重生的辣妹男娘飞向极乐世界吧！！',
        choices: [
          {
            id: 'c10_surrender_ending',
            text: '（在无尽的痉挛与失神中，泪流满面地彻底雌堕沦陷）',
            attitude: 'submissive',
            replyDialogue: '欢迎来到我们黑皮男娘的新世界~ 以后每天晚上，我们都是最亲密无间的主仆与姐妹了哦~',
            hardwareAction: { type: 'toy_pattern', target: 'climax_milking', durationSec: 30 },
            nextStepId: 'ending',
            endingTitle: '💖 结局：更衣室的永恒极乐雌堕',
            endingDesc: '经过 10 幕严酷与甜美交织的深度文学级身心重塑，你的男性自尊彻底灰飞烟灭，身心完全同化为娇媚服从的黑皮辣妹男娘，永远沉浸在被 Ren 支配的极乐与幸福中。',
            endingType: 'surrender',
          },
        ],
      },
    },
  },

  // 剧本 2: 《赛博圣修女的圣洁赎罪洗礼》 (约 3200 字沉浸短篇)
  {
    id: 'femboy_cyber_nun',
    title: '赛博圣修女的圣洁赎罪洗礼',
    subtitle: '在冰冷肃穆的机械大教堂忏悔室，冷面修女索菲亚用 10 道圣诫重塑你的罪孽之躯...',
    category: '雌堕身心重塑',
    isFemboy: true,
    avatar: '⛪',
    bgGradient: 'from-purple-950 via-slate-900 to-indigo-950',
    difficulty: '⭐⭐⭐⭐⭐ (禁欲圣洁与堕落极乐)',
    tags: ['赛博修女', '忏悔室', '圣水灌洗', '戒律电击', '10幕史诗洗礼'],
    description: '赛博大教堂深处的地下忏悔舱，高耸的金属十字架在幽蓝的光束下投下巨大的阴影。冷面修女索菲亚转动着手中的银质念珠，手持带金色圣痕的高压水管与电极锁，以 10 轮不容置疑的神圣戒律，开启了对你肉体与灵魂的彻底净化...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '忏悔室厚重的铅门在身后沉重合拢，空气中弥漫着乳香与机油的混合气味。索菲亚修女端立在机械圣坛前，冰蓝色的义眼在黑暗中闪烁着毫无温度的光芒。她手中的金属教鞭轻轻点在你的胸口。',
        dialogue: '迷途的罪人，你的肉体里流淌着世俗肮脏的雄性欲望与傲慢。跪在圣坛的冷铁地板上，向主坦白你隐藏在内腑深处的全部罪孽！',
        choices: [
          {
            id: 'c1_kneel_pray',
            text: '（双膝跪倒在冷铁地面上）我有罪... 请修女为我洗涤肉体的罪恶...',
            attitude: 'submissive',
            replyDialogue: '迷途知返的羔羊尚有救赎的可能。受领初阶圣律微流洗礼，感受圣火的灼热吧！',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 10 },
            nextStepId: 'step_2',
          },
          {
            id: 'c1_rebel_nun',
            text: '（站立不肯下跪）这是迷信和非法拘禁！我没有任何罪！',
            attitude: 'defiant',
            replyDialogue: '执迷不悟的顽劣罪徒！圣诫之雷将彻底粉碎你的傲慢与筋骨！',
            hardwareAction: { type: 'ems_wave', target: 'electric_sting', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '微电流如圣光般在你的四肢百骸游走，索菲亚从祭坛的暗格中取出了一具通体由纯银打造的禁欲贞洁圣锁。圣锁内部布满了细小的触控感应片。',
        dialogue: '第一诫：剥夺雄性欲望之源。罪恶的根源就在于这根充满贪婪与躁动的器官。以圣光之名，戴上禁欲圣锁，在洗礼完成前，剥夺你的一切自决权！',
        choices: [
          {
            id: 'c2_lock_on',
            text: '（顺从地任由修女将圣锁锁死在前端）愿圣锁锁住我的罪孽...',
            attitude: 'submissive',
            replyDialogue: '圣锁已彻底闭合。你已不再拥有身为男性的权利，唯有服从。',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 15 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '修女连接上了高压智能圣水灌注机，冰凉的导管缓缓探入你的后庭。伴随着机械水泵的低吟，温热的净化圣水顺着管道奔涌而入。',
        dialogue: '第二诫：圣水净化脏腑。感受这股神圣的充盈感在你体内蔓延。记住，未经恩准，若是漏出一滴圣水，便是对神殿最大的亵渎！',
        choices: [
          {
            id: 'c3_hold_holy_water',
            text: '（死死收紧括约肌，腹部鼓起）肚子好胀... 弟子在拼死憋住...',
            attitude: 'submissive',
            replyDialogue: '保持住这份神圣的充盈。水压提升 50ml，感受神恩的重量！',
            hardwareAction: { type: 'enema_pattern', target: 'slow_fill', durationSec: 20 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '腹部的胀满感越来越沉重，索菲亚修女亲手为你披上了一袭洁白的修女长袍，并将纯白的长头纱系在你的发间。',
        dialogue: '第三诫：褪去凡身。换上圣洁的修女袍，从今往后，你不再是尘世的男人，而是属于赛博神殿的见习修女。',
        choices: [
          {
            id: 'c4_wear_habit',
            text: '（低头看着纯白的修女袍）我是见习修女... 愿为主奉献一切...',
            attitude: 'submissive',
            replyDialogue: '圣洁的心智正在重塑。启动前列腺深层圣律脉冲！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 20 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '体内的震动器械精准撞击在前列腺上，配合圣水的压迫，每一次脉冲都激起一阵阵直冲脑髓的酸麻感，你的声音变得娇软而颤抖。',
        dialogue: '第四诫：以娇柔之声祈祷。念诵忏悔圣经第一章，声音要恭顺、要甜美，像真正的修女那般！',
        choices: [
          {
            id: 'c5_chant_prayer',
            text: '（带着哭腔娇吟念诵）主啊... 宽恕我这具淫靡的雌身... 赐我纯洁...',
            attitude: 'submissive',
            replyDialogue: '多么纯净悦耳的忏悔之音。赐予你更深层次的锯齿圣电！',
            hardwareAction: { type: 'ems_wave', target: 'sawtooth_climb', durationSec: 20 },
            nextStepId: 'step_6',
          },
        ],
      },
      step_6: {
        id: 'step_6',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '快感与圣水压力同时冲向最高峰，你整个人瘫倒在修女脚边，即将迎来高潮！索菲亚瞬间切断了电源！',
        dialogue: '（0.05秒毫秒级急刹断电）第五诫：禁欲戒律！高潮是神圣的恩赏，未获许可擅自释放即为重罪！给我把欲望咽回去！',
        choices: [
          {
            id: 'c6_beg_nun_release',
            text: '（抱住修女的黑色裙摆哀求）索菲亚大人... 求您赐予恩典... 弟子快要被憋疯了...',
            attitude: 'begging',
            replyDialogue: '懂得求饶才有救赎。在冷场中静心反省 15 秒！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_7',
          },
        ],
      },
      step_7: {
        id: 'step_7',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '索菲亚修女用圣水浸湿手指，在你的额头画下十字圣痕。',
        dialogue: '第六诫：终身誓约。你的雄性傲慢已在圣水与雷电中熔化。你是否发誓终身留在赛博神殿，作为服从我的见习修女？',
        choices: [
          {
            id: 'c7_vow_forever',
            text: '（虔诚亲吻修女手背）弟子发誓... 终身侍奉索菲亚修女与圣殿...',
            attitude: 'submissive',
            replyDialogue: '善哉。重开双通道神圣脉冲！',
            hardwareAction: { type: 'toy_pattern', target: 'deep_pulse', durationSec: 25 },
            nextStepId: 'step_8',
          },
        ],
      },
      step_8: {
        id: 'step_8',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '水泵开启了最后的充能，腹部的饱胀与体内的马达全速共振，带来神圣而狂暴的快感冲击。',
        dialogue: '第七诫：神圣共鸣！感受神迹在你的雌性躯体内激荡！大声赞美神恩！',
        choices: [
          {
            id: 'c8_praise_loud',
            text: '（仰起脖颈尖叫赞美）赞美圣殿！赞美索菲亚大人——！！',
            attitude: 'submissive',
            replyDialogue: '虔诚的呐喊！马达功率调至 18 档！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_18', durationSec: 20 },
            nextStepId: 'step_9',
          },
        ],
      },
      step_9: {
        id: 'step_9',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '全忏悔室的光芒全部化为刺目的白金色，索菲亚修女解开了禁欲圣锁，将遥控器推到了最高档。',
        dialogue: '第八诫：神圣大救赎！见习修女，现在，以神之名，赐予你终极洗礼大释放！！',
        choices: [
          {
            id: 'c9_holy_climax_now',
            text: '（在圣光中彻底沦陷，迎来神圣无触干射大绝顶）',
            attitude: 'submissive',
            replyDialogue: '在圣洁的极乐中重生吧！！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'step_10',
          },
        ],
      },
      step_10: {
        id: 'step_10',
        speaker: '圣修女 索菲亚',
        avatar: '⛪',
        narrative: '【第 10 幕 · 赛博圣殿终极救赎】圣水喷涌而出，前列腺在 20 档超频与电击狂暴中迎来长达 30 秒的终极大喷发！',
        dialogue: '（轻抚你汗湿的长发）安息在主的怀抱里吧。从今往后，你就是神殿最圣洁的专属雌奴修女。',
        choices: [
          {
            id: 'c10_holy_ending',
            text: '（瘫倒在圣坛前，带着解脱的微笑彻底皈依）',
            attitude: 'submissive',
            replyDialogue: '阿门。',
            hardwareAction: { type: 'toy_pattern', target: 'breathe', durationSec: 20 },
            nextStepId: 'ending',
            endingTitle: '⛪ 结局：赛博圣修女的永恒皈依',
            endingDesc: '历经 10 幕圣诫与圣水洗礼，你褪尽了世俗男性的浮躁与罪孽，作为身心彻底雌化的圣殿见习修女，永远侍奉在索菲亚修女的身边。',
            endingType: 'surrender',
          },
        ],
      },
    },
  },

  // 剧本 3: 《魅魔高校的特等雌奴改造课》 (长篇 3000 字)
  {
    id: 'femboy_succubus_school',
    title: '魅魔高校的特等雌奴改造课',
    subtitle: '误入魅魔学院的地下实训室，恶魔导师莉莉丝用 10 堂实训课将你改造成顶级玩物...',
    category: '雌堕身心重塑',
    isFemboy: true,
    avatar: '😈',
    bgGradient: 'from-fuchsia-950 via-slate-900 to-pink-950',
    difficulty: '⭐⭐⭐⭐⭐ (极度榨干 · 灵魂出窍)',
    tags: ['魅魔导师', '恶魔尾巴', '媚药渗透', '10幕深度改造'],
    description: '魅魔女子学院的地下实践课教室，空气中弥漫着甜腻的粉色烟雾。恶魔导师莉莉丝用皮鞭挑起你的下巴。10 堂必修课程包含穿戴魅魔尾巴、媚药电流渗透与彻底雌化思维...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '地下课室的粉红烛光摇曳，莉莉丝导师头顶的恶魔角微微发亮，手里甩动着带微电极的粉色魅魔尾巴。',
        dialogue: '欢迎来到魅魔学院的特别课室~ 听说人类男性的自尊心最脆弱了？今天这 10 堂实训课，我会把你改造成全校最听话的特等小雌奴哦~',
        choices: [
          {
            id: 'c1_sub',
            text: '（跪在讲台前）请莉莉丝老师指教...',
            attitude: 'submissive',
            replyDialogue: '态度真端正~ 奖励你一记酥麻的微电流入门课！',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '莉莉丝拿起带吸盘电极的粉色恶魔尾巴，尾巴内部是一根高频旋转震动棒。',
        dialogue: '第 2 课：魅魔尾巴植入。男孩子翘起尾椎骨的样子最可爱了，自己把它推进去，让尾巴在身后摇起来！',
        choices: [
          {
            id: 'c2_tail_in',
            text: '（红着脸推进后方）尾巴... 推进去了... 在身后晃动...',
            attitude: 'submissive',
            replyDialogue: '摇尾巴的样子太乖了！启动尾部 8 档高频震颤！',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 20 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '尾巴在你的体内疯狂蠕动，莉莉丝拿出一件极具挑逗性的露胸魅魔紧身皮衣。',
        dialogue: '第 3 课：仪态改造。把这件皮衣换上，胸前贴上电极片。我要你像小母狗一样趴在地上叫！',
        choices: [
          {
            id: 'c3_wear_suit',
            text: '（穿上皮衣趴下）汪... 莉莉丝主人... 我穿好了...',
            attitude: 'submissive',
            replyDialogue: '汪汪叫的声音真甜~ 启动双通道心跳脉冲！',
            hardwareAction: { type: 'ems_wave', target: 'pulse_train', durationSec: 15 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '微电流如火蛇般在你的胸部和后腰游走，莉莉丝踩着高跟鞋踩在你的背上。',
        dialogue: '第 4 课：敏感度拓展。你的前列腺现在应该像火烧一样敏感了吧？马达加速到九浅一深！',
        choices: [
          {
            id: 'c4_endure',
            text: '（身体剧烈扭动）顶得太深了... 脑袋要烧焦了...',
            attitude: 'begging',
            replyDialogue: '就是要烧焦你无聊的理智！享受它！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 20 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '快感如潮水般冲击，莉莉丝俯下身，红唇几乎贴在你的耳畔。',
        dialogue: '第 5 课：雌奴思维重构。大声说三遍：“我是莉莉丝老师的下等雌奴！”',
        choices: [
          {
            id: 'c5_chant_slave',
            text: '（抽泣大喊）我是莉莉丝老师的下等雌奴！我是雌奴！',
            attitude: 'submissive',
            replyDialogue: '优秀学员！满分！奖励你深层电击波形！',
            hardwareAction: { type: 'ems_wave', target: 'sawtooth_climb', durationSec: 20 },
            nextStepId: 'step_6',
          },
        ],
      },
      step_6: {
        id: 'step_6',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '就在你即将喷发的千钧一发之际，莉莉丝按下了急刹键！所有电流与马达戛然而止！',
        dialogue: '（0.05秒急刹断电）第 6 课：魅魔控射礼仪！没得到导师许可，擅自射精直接记大过！憋住！',
        choices: [
          {
            id: 'c6_beg_mercy',
            text: '（疯狂抓挠地面）老师... 憋不住了... 求你让我射...',
            attitude: 'begging',
            replyDialogue: '憋不住也得憋！冷场 15 秒！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_7',
          },
        ],
      },
      step_7: {
        id: 'step_7',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '莉莉丝拿出一支紫色的媚药药剂，滴在你的舌尖上，带来一阵火辣辣的甘甜。',
        dialogue: '第 7 课：身心彻底融化。媚药已经生效，你的每一个细胞都在渴望做个淫荡的小男娘~ 对不对？',
        choices: [
          {
            id: 'c7_agree',
            text: '（神志不清痴笑）对... 我想做小男娘... 想被老师狠狠玩弄...',
            attitude: 'submissive',
            replyDialogue: '这才是好学生嘛~ 重启马达 16 档！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_16', durationSec: 20 },
            nextStepId: 'step_8',
          },
        ],
      },
      step_8: {
        id: 'step_8',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '恶魔尾巴在你的体内疯狂搅动，电流如狂雷般在体内爆开，整个教室回荡着你的娇喘。',
        dialogue: '第 8 课：极限耐受测试！挺过这 20 秒的全通道雷暴，你就是全校最优秀的特等雌奴！',
        choices: [
          {
            id: 'c8_endure_storm',
            text: '（仰起脖颈承受狂暴电击）啊啊啊——！！莉莉丝大人！！',
            attitude: 'submissive',
            replyDialogue: '太壮观了！肉体已经彻底熟透了！',
            hardwareAction: { type: 'ems_wave', target: 'storm_surge', durationSec: 20 },
            nextStepId: 'step_9',
          },
        ],
      },
      step_9: {
        id: 'step_9',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '莉莉丝跨坐在你的身上，用手捧起你满是汗水与泪水的脸蛋。',
        dialogue: '第 9 课：毕业誓约。亲吻我的戒指，从今往后，你就是属于魅魔高校的永久私有财产！',
        choices: [
          {
            id: 'c9_kiss_ring',
            text: '（虔诚亲吻恶魔戒指）我愿意... 永远做莉莉丝老师的私有财产...',
            attitude: 'submissive',
            replyDialogue: '恭喜你！10 门课程全优毕业！现在执行毕业狂欢大释放！！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'step_10',
          },
        ],
      },
      step_10: {
        id: 'step_10',
        speaker: '魅魔导师 莉莉丝',
        avatar: '😈',
        narrative: '【第 10 幕 · 魅魔毕业终极榨干】全马达拉满 20 档超频，电流与前列腺疯狂撞击，带来整整 30 秒的灵魂出窍大高潮！',
        dialogue: '（娇笑喘息）射出来吧！把所有的精气全部献给魅魔学院吧！！',
        choices: [
          {
            id: 'c10_succubus_ending',
            text: '（身体抽搐，在无尽的极乐中彻底雌化蜕变）',
            attitude: 'submissive',
            replyDialogue: '好棒的精气~ 以后每天晚上都要来地下课室上课哦~',
            hardwareAction: { type: 'toy_pattern', target: 'climax_milking', durationSec: 30 },
            nextStepId: 'ending',
            endingTitle: '😈 结局：魅魔高校的特等看板雌奴',
            endingDesc: '你以满分成绩通过了莉莉丝导师的 10 轮雌堕改造课，身体已完全适应魅魔尾巴与高潮榨干，成为学院最引以为傲的专属特等男娘侍从。',
            endingType: 'surrender',
          },
        ],
      },
    },
  },

  // 剧本 4: 《深闺千金的绝对服从女仆调教》 (长篇 3000 字)
  {
    id: 'femboy_maid_mansion',
    title: '深闺千金的绝对服从女仆调教',
    subtitle: '被卖入豪门庄园，恶魔大小姐克莱尔用 10 条严苛家规将你训为贴身女仆...',
    category: '雌堕身心重塑',
    isFemboy: true,
    avatar: '🎀',
    bgGradient: 'from-amber-950 via-slate-900 to-rose-950',
    difficulty: '⭐⭐⭐⭐ (豪门规矩与极致羞耻)',
    tags: ['傲慢大小姐', '女仆家规', '跪侍斟茶', '10幕深度规训'],
    description: '庄园二楼的奢华寝室内，千金大小姐克莱尔端坐于丝绒沙发上。10 条绝对服从家规逐步展开...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '欧式壁炉里火光跳动，克莱尔大小姐优雅地摇晃着红酒杯，脚尖轻挑着一条女仆围裙。',
        dialogue: '既然签下了卖身契，从今天起你就是我的贴身小女仆了。管家没教过你见到主人要下跪行礼吗？',
        choices: [
          {
            id: 'c1_kneel',
            text: '（屈膝下跪）大小姐安康... 女仆给您请安...',
            attitude: 'submissive',
            replyDialogue: '哼，还算识趣。先给你通上规矩电极，让你长长记性！',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '微电流沿着大腿内侧蔓延，大小姐用折扇轻敲你的脸颊。',
        dialogue: '家规第二条：女仆必须随时随地保持体态优雅。把这条带铃铛的金属感官塞推进去，走路如果发出响声就要受罚！',
        choices: [
          {
            id: 'c2_insert_plug',
            text: '（羞耻地推入体内）推进去了... 冰冰凉凉的...',
            attitude: 'submissive',
            replyDialogue: '很好。现在站起来，走两步给我看看~',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 15 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '感官塞在你的体内随着步伐轻轻碰撞，铃铛发出叮当微响，激起阵阵难耐的快感。',
        dialogue: '家规第三条：为主人斟红酒。跪着爬过来，用嘴叼着酒杯递给我！',
        choices: [
          {
            id: 'c3_serve_wine',
            text: '（双手撑地爬过去，嘴叼酒杯送上）',
            attitude: 'submissive',
            replyDialogue: '真像只乖巧的母狗女仆呢~ 赏你一口红酒！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 20 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '红酒顺着你的下巴滴在女仆围裙上，克莱尔拿出了电击遥控器。',
        dialogue: '家规第四条：女仆必须学会忍受主人的喜怒无常。现在我要毫无理由地上调电击强度，不许叫出声！',
        choices: [
          {
            id: 'c4_endure_pain',
            text: '（死死咬住嘴唇，浑身颤抖忍受电击）唔...！',
            attitude: 'submissive',
            replyDialogue: '忍耐的样子真惹人怜爱。再加一档！',
            hardwareAction: { type: 'ems_wave', target: 'pinch_crescendo', durationSec: 15 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '体内和体外的刺激双重爆发，你的前列腺被持续施压，眼角渗出泪水。',
        dialogue: '家规第五条：女仆的心里只能有主人一人。告诉我，你现在满脑子想的都是谁？',
        choices: [
          {
            id: 'c5_only_claire',
            text: '（娇喘哭喊）克莱尔大小姐！我心里只有大小姐！',
            attitude: 'submissive',
            replyDialogue: '回答正确~ 调教进度过半，开启强力旋转！',
            hardwareAction: { type: 'toy_pattern', target: 'vacuum_lock', durationSec: 20 },
            nextStepId: 'step_6',
          },
        ],
      },
      step_6: {
        id: 'step_6',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '强烈的快感即将突破阈值，大小姐面无表情地按下了断电按钮！',
        dialogue: '（0.05秒急刹断电）家规第六条：高潮剥夺！下人擅自高潮是不可饶恕的重罪！给我憋回去！',
        choices: [
          {
            id: 'c6_beg_claire',
            text: '（抱住大小姐的双腿哀求）求大小姐开恩... 让我释放吧...',
            attitude: 'begging',
            replyDialogue: '看你这副饥渴可怜的样子~ 罚你冷场反省 15 秒！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_7',
          },
        ],
      },
      step_7: {
        id: 'step_7',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '克莱尔大小姐用脚尖挑起你的下巴，眼神中满是高傲与征服感。',
        dialogue: '家规第七条：认领专属印记。在这个契约书上按上手印，承认自己永远是我的专属奴仆！',
        choices: [
          {
            id: 'c7_sign_contract',
            text: '（颤抖着按上手印）我按了... 我永远是大小姐的奴仆...',
            attitude: 'submissive',
            replyDialogue: '契约成立！重启马达与深层电波！',
            hardwareAction: { type: 'toy_pattern', target: 'deep_pulse', durationSec: 25 },
            nextStepId: 'step_8',
          },
        ],
      },
      step_8: {
        id: 'step_8',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '体内的器械重新疯狂运转，大小姐将两枚夹子电极夹在了你的敏感部位。',
        dialogue: '家规第八条：全面感官服从！感受全方位的电流轰炸，喊出你最羞耻的服从宣言！',
        choices: [
          {
            id: 'c8_yell_maid',
            text: '（放声大叫）我是大小姐的一条小母狗女仆！！',
            attitude: 'submissive',
            replyDialogue: '真动听~ 马达调速推至 18 档！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_18', durationSec: 20 },
            nextStepId: 'step_9',
          },
        ],
      },
      step_9: {
        id: 'step_9',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '大小姐轻抚着你的头发，眼神中终于露出了满意的温柔笑意。',
        dialogue: '家规第九条：忠诚奖赏。10 条家规你完成得非常出色，大小姐今晚特许你高潮！',
        choices: [
          {
            id: 'c9_ready_climax',
            text: '（激动落泪）谢大小姐恩赐！！请尽情榨干我！！',
            attitude: 'submissive',
            replyDialogue: '终极大招——开启全速 20 档超频！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'step_10',
          },
        ],
      },
      step_10: {
        id: 'step_10',
        speaker: '恶魔千金 克莱尔',
        avatar: '🎀',
        narrative: '【第 10 幕 · 豪门千金终极恩典】20 档马达与双通道高压电击全面轰鸣，在整整 30 秒的极乐狂潮中将你彻底榨空！',
        dialogue: '（低头看着你）我的专属小女仆，以后每天晚上，都要像这样跪着侍奉我哦~',
        choices: [
          {
            id: 'c10_maid_ending',
            text: '（瘫软在大小姐脚下，幸福地闭上双眼）',
            attitude: 'submissive',
            replyDialogue: '乖孩子，辛苦了。',
            hardwareAction: { type: 'toy_pattern', target: 'breathe', durationSec: 20 },
            nextStepId: 'ending',
            endingTitle: '🎀 结局：豪门千金的终身专属女仆',
            endingDesc: '你完美通过了 10 条严苛的豪门女仆家规，身心彻底完成女性化重塑，永远作为克莱尔大小姐最宠爱的贴身专属小女仆生活在庄园深处。',
            endingType: 'surrender',
          },
        ],
      },
    },
  },

  // 剧本 5: 《前列腺深度觉醒与后穴雌化手术》 (长篇 3000 字)
  {
    id: 'femboy_prostate_awakening',
    title: '前列腺深度觉醒与后穴雌化手术',
    subtitle: '赛博生物研究所内，白大褂机械医师用 10 道神经脉冲彻底重塑你的快感中枢...',
    category: '雌堕身心重塑',
    isFemboy: true,
    avatar: '⚡',
    bgGradient: 'from-cyan-950 via-slate-900 to-blue-950',
    difficulty: '⭐⭐⭐⭐⭐ (生理中枢彻底改造)',
    tags: ['机械医师', '生物神经重塑', '前列腺大高潮', '10幕深度手术'],
    description: '在冰冷的赛博手术台上，四肢被磁力环固定。机械医师启动了 10 阶段神经重塑程序，将你的快感中枢从前端彻底转移至前列腺与后庭...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '手术室无影灯亮起，艾米丽医师推着神经调控推车来到手术台前。',
        dialogue: '实验体 07 号，欢迎来到神经感官重塑手术。今天我们将进行 10 阶段快感中枢迁移手术，准备好接受洗礼了吗？',
        choices: [
          {
            id: 'c1_agree_surgery',
            text: '（被绑在手术台上）请...请医师开始手术...',
            attitude: 'submissive',
            replyDialogue: '很好，心理准备很充分。先进行神经微流校准！',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '微电流通过贴片传导至脊髓神经节，艾米丽将一支高精度的医疗级探针缓缓推入你的体内。',
        dialogue: '阶段 2：探针植入。这根探针带有 16 个压力传感器，正在精准锁定你的前列腺 G 点核心。',
        choices: [
          {
            id: 'c2_probe_in',
            text: '（身体紧绷微颤）顶到了... 里面酸酸麻麻的...',
            attitude: 'submissive',
            replyDialogue: '信号锁定成功！开始低频共振催化！',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 20 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '探针开始以特定频率旋转，艾米丽在前端戴上了神经阻断环。',
        dialogue: '阶段 3：前端感觉阻断。现在你前面的器官已被完全麻痹，你只能依靠后方的刺激获取快感！',
        choices: [
          {
            id: 'c3_front_block',
            text: '（低头看着前面毫无感觉）前面真的麻木了... 只能靠后面了...',
            attitude: 'submissive',
            replyDialogue: '这就对了！神经回路正在强制重定向！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 20 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '后方探针的每一次抽动都直接引爆大脑中枢，你的身体不受控制地剧烈抽搐。',
        dialogue: '阶段 4：前列腺神经突触增生。加大双极电脉冲，强制催化前列腺感受器增殖 300%！',
        choices: [
          {
            id: 'c4_surge_pain',
            text: '（弓起背部尖叫）好强烈... 感觉快感像电流一样炸开了！！',
            attitude: 'begging',
            replyDialogue: '神经增殖成功！感受器灵敏度已达到雌性水平！',
            hardwareAction: { type: 'ems_wave', target: 'sawtooth_climb', durationSec: 20 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '艾米丽看着心电监控仪，屏幕上的心率飙升到了 145 BPM。',
        dialogue: '阶段 5：心智雌化认知测试。在你的大脑回路里，现在的你最享受哪个部位带来的快感？',
        choices: [
          {
            id: 'c5_back_pleasure',
            text: '（眼神迷离大口喘息）后面... 最喜欢后穴和前列腺的快感...',
            attitude: 'submissive',
            replyDialogue: '认知迁移完毕！启动深层绞磨程式！',
            hardwareAction: { type: 'toy_pattern', target: 'vacuum_lock', durationSec: 20 },
            nextStepId: 'step_6',
          },
        ],
      },
      step_6: {
        id: 'step_6',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '你的腹部剧烈抽搐，即将迎来人生中第一次纯前列腺无触干射高潮！艾米丽按下了急刹键！',
        dialogue: '（0.05秒急刹断电）阶段 6：耐受阈值拉扯！初次前列腺高潮必须经过 3 次边缘控射淬炼！深呼吸，咽回去！',
        choices: [
          {
            id: 'c6_beg_doctor',
            text: '（泪流满面哀求）艾米丽医师... 求你让我高潮吧... 我受不了了...',
            attitude: 'begging',
            replyDialogue: '为了手术完美成功，必须耐受！冷场 15 秒！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_7',
          },
        ],
      },
      step_7: {
        id: 'step_7',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '探针重新启动，这次以极其缓慢深沉的频率直接顶压在前列腺最核心处。',
        dialogue: '阶段 7：深层神经固化。感受这种被持续填满和压迫的酸麻感，你的身体已经永远回不去了。',
        choices: [
          {
            id: 'c7_accept_fate',
            text: '（瘫软在手术台上）我已经... 彻底变成这根探针的形状了...',
            attitude: 'submissive',
            replyDialogue: '非常完美的手术配合度！启动 16 档超频！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_16', durationSec: 25 },
            nextStepId: 'step_8',
          },
        ],
      },
      step_8: {
        id: 'step_8',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '艾米丽将电流调到了暴风雨模式，手术台四周的示波器全部疯狂跳动。',
        dialogue: '阶段 8：终极神经重载测试！双通道电流全开，迎接前所未有的神经风暴！',
        choices: [
          {
            id: 'c8_storm_cry',
            text: '（尖叫着承受风暴）啊啊啊啊——！！',
            attitude: 'submissive',
            replyDialogue: '神经中枢已 100% 雌化重构完毕！',
            hardwareAction: { type: 'ems_wave', target: 'storm_surge', durationSec: 20 },
            nextStepId: 'step_9',
          },
        ],
      },
      step_9: {
        id: 'step_9',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '艾米丽解开了所有的束缚带，但你已经浑身无力瘫软，只能依赖探针支撑。',
        dialogue: '阶段 9：手术终局评估。实验体 07 号，你现在正式通过全部改造，准备好迎接终极释放了吗？',
        choices: [
          {
            id: 'c9_ready_final',
            text: '（用尽最后力气点头）准备好了... 赐予我前列腺高潮吧！！',
            attitude: 'submissive',
            replyDialogue: '终极大招——全频段 20 档终极榨干爆发！！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'step_10',
          },
        ],
      },
      step_10: {
        id: 'step_10',
        speaker: '机械医师 艾米丽',
        avatar: '⚡',
        narrative: '【第 10 幕 · 终极前列腺神经升华】探针以 20 档极限转速在前列腺核心持续轰击，不需要触碰前端，你迎来了长达 30 秒的纯前列腺无触干射大喷发！',
        dialogue: '（记录实验数据）手术完美成功！祝贺你，从今往后，你就是拥有完美雌性快感中枢的顶级肉体了。',
        choices: [
          {
            id: 'c10_surgery_ending',
            text: '（在极致的痉挛与失神中，泪流满面地完成了神经重塑）',
            attitude: 'submissive',
            replyDialogue: '好好休息吧，我的杰作。',
            hardwareAction: { type: 'toy_pattern', target: 'climax_milking', durationSec: 30 },
            nextStepId: 'ending',
            endingTitle: '⚡ 结局：前列腺快感中枢彻底觉醒',
            endingDesc: '经过 10 阶段精密残酷的神经改造手术，你的男性快感回路彻底被抹去，身体完全进化为仅凭后穴与前列腺就能迎来无尽大高潮的终极雌堕体质。',
            endingType: 'surrender',
          },
        ],
      },
    },
  },

  // ==========================================
  // 🐺 经典硬核支配专区 (文学级万字长篇)
  // ==========================================

  // 剧本 6: 《暗夜审讯室：黑客特工的绝对服从》 (长篇 3500 字)
  {
    id: 'dom_interrogation',
    title: '暗夜审讯室：黑客特工的绝对服从',
    subtitle: '被捕入地下三层审讯密室，冷面审讯官狼牙用 10 道严苛刑讯逼你交出核心密匙...',
    category: '经典硬核支配',
    isFemboy: false,
    avatar: '🐺',
    bgGradient: 'from-slate-950 via-zinc-900 to-neutral-950',
    difficulty: '⭐⭐⭐⭐⭐ (硬核严苛支配)',
    tags: ['冷酷男S', '审讯椅', '电击逼供', '意志瓦解', '10幕硬核小说'],
    description: '地下三层的黑客审讯密室，厚重的防爆钢门被彻底锁死。冷面审讯官狼牙拉开铁椅，点燃一支香烟。10 轮严苛审讯逐步摧毁你的心理防线...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '铁椅上的手铐和脚镣冰冷刺骨，审讯官狼牙点燃一支香烟，居高临下地俯视着你。',
        dialogue: '代号“幽灵”的黑客特工，落到我手里还想全身而退？交出核心解密密钥，否则这 10 道审讯电流会让你跪着求饶！',
        choices: [
          {
            id: 'c1_resist',
            text: '（咬牙瞪着他）我什么都不会说的！死了这条心吧！',
            attitude: 'defiant',
            replyDialogue: '有骨气！我就喜欢嘴硬的猎物，先来尝尝开胃菜！',
            hardwareAction: { type: 'ems_wave', target: 'electric_sting', durationSec: 10 },
            nextStepId: 'step_2',
          },
          {
            id: 'c1_nervous',
            text: '（声音发颤）别动粗... 我们可以谈谈条件...',
            attitude: 'begging',
            replyDialogue: '在我的审讯室里，只有服从，没有谈判！通电！',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '电流刺痛让你全身肌肉瞬间痉挛，狼牙将电极片紧紧贴在你的腹肌两侧。',
        dialogue: '第一道拷问：谁是指使你的幕后上线？说！',
        choices: [
          {
            id: 'c2_hold',
            text: '（痛得闷哼）唔... 绝不背叛组织...',
            attitude: 'defiant',
            replyDialogue: '忠诚？那就看看你的肉体能不能抗住第二档持续脉冲！',
            hardwareAction: { type: 'ems_wave', target: 'pulse_train', durationSec: 15 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '持续的脉冲轰击让你大汗淋漓，狼牙拿出了震动器械连接到你的下半身。',
        dialogue: '看来纯肉体痛苦对你不够刺激。那就加上快感折磨！启动 8 档慢速绞磨！',
        choices: [
          {
            id: 'c3_confused',
            text: '（痛苦与快感交织）你... 你竟然用这种卑鄙手段...',
            attitude: 'begging',
            replyDialogue: '只要能拿到情报，任何手段都是正义的！',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 20 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '电击与马达同时施压，你的身体不受控制地在铁椅上扭动，意志开始出现裂痕。',
        dialogue: '第四道拷问：交出服务器密码的前四位！否则立刻把档位翻倍！',
        choices: [
          {
            id: 'c4_partial_code',
            text: '（气喘吁吁，意志动摇）我说... 前四位是 7041...',
            attitude: 'submissive',
            replyDialogue: '这才乖嘛。但还不够，继续施压！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 20 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '狼牙俯下身，冰冷的手套捏住你的下巴，直视你涣散的瞳孔。',
        dialogue: '第五道拷问：看着我的眼睛！你现在是谁的手下败将？',
        choices: [
          {
            id: 'c5_admit_defeat',
            text: '（声音嘶哑）是... 是长官的手下败将...',
            attitude: 'submissive',
            replyDialogue: '认清自己的地位了。波形升级为锯齿爬升！',
            hardwareAction: { type: 'ems_wave', target: 'sawtooth_climb', durationSec: 20 },
            nextStepId: 'step_6',
          },
        ],
      },
      step_6: {
        id: 'step_6',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '快感累积到临界，你忍不住大声求饶想要射精，狼牙瞬间切断电源！',
        dialogue: '（0.05秒急刹断电）第六道拷问：审讯期间严禁高潮！把最后四位密码交代出来，我才会考虑给你释放！',
        choices: [
          {
            id: 'c6_beg_officer',
            text: '（痛苦挣扎）最后四位是 9982！全部告诉你了！求求你让我射吧！',
            attitude: 'begging',
            replyDialogue: '密码验证通过！但审讯规矩还没完！冷场 15 秒！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_7',
          },
        ],
      },
      step_7: {
        id: 'step_7',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '狼牙确认了密码，嘴角扬起一抹冷酷的微笑。',
        dialogue: '第七道拷问：你已经出卖了所有的秘密。从现在起，你只能做我的秘密线人与私有玩物，听懂了吗？',
        choices: [
          {
            id: 'c7_agree_slave',
            text: '（彻底放弃抵抗）听懂了... 永远听从长官调遣...',
            attitude: 'submissive',
            replyDialogue: '很好。重启全套器械，开始身心烙印！',
            hardwareAction: { type: 'toy_pattern', target: 'deep_pulse', durationSec: 25 },
            nextStepId: 'step_8',
          },
        ],
      },
      step_8: {
        id: 'step_8',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '马达与电流再次轰鸣，狼牙解开手铐，命令你跪在地上抱住他的军靴。',
        dialogue: '第八道规矩：亲吻我的军靴，展示你的忠诚！',
        choices: [
          {
            id: 'c8_kiss_boot',
            text: '（跪在地上亲吻军靴）长官... 我彻底服从您...',
            attitude: 'submissive',
            replyDialogue: '像条忠诚的军犬！马达拉到 18 档！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_18', durationSec: 20 },
            nextStepId: 'step_9',
          },
        ],
      },
      step_9: {
        id: 'step_9',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '狼牙将遥控器推到了最高档，审讯室内的红灯狂闪。',
        dialogue: '第九道仪式：终极受刑与赏赐！准备迎接属于你的审讯大高潮！',
        choices: [
          {
            id: 'c9_ready_climax',
            text: '（仰天尖叫，彻底臣服）长官！长官——！！',
            attitude: 'submissive',
            replyDialogue: '终极大招——全速榨干！！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'step_10',
          },
        ],
      },
      step_10: {
        id: 'step_10',
        speaker: '审讯官 狼牙 (男S)',
        avatar: '🐺',
        narrative: '【第 10 幕 · 审讯终极服从大释放】全功率 20 档超频与电击狂暴轰鸣，你在长达 30 秒的极乐痉挛中彻底丧失了一切抵抗意志！',
        dialogue: '（将外套披在你身上）审讯结束。今后，你就是我最听话的私密猎犬。',
        choices: [
          {
            id: 'c10_interrogation_ending',
            text: '（瘫软在审讯官脚边，彻底服从）',
            attitude: 'submissive',
            replyDialogue: '带你回我的私人住所，好好休整。',
            hardwareAction: { type: 'toy_pattern', target: 'breathe', durationSec: 20 },
            nextStepId: 'ending',
            endingTitle: '🐺 结局：暗夜审讯官的专属特工猎犬',
            endingDesc: '经过 10 幕残酷与快感并存的硬核审讯，你交出了所有机密，意志与肉体被狼牙审讯官彻底征服，成为他唯一的私属特工猎犬。',
            endingType: 'surrender',
          },
        ],
      },
    },
  },

  // 剧本 7: 《女王高座下的跪侍契约》 (长篇 3000 字)
  {
    id: 'dom_queen_throne',
    title: '女王高座下的跪侍契约',
    subtitle: '踏入冷艳女王的宫殿，10 道尊卑戒律考验你的忍耐极限...',
    category: '经典硬核支配',
    isFemboy: false,
    avatar: '👑',
    bgGradient: 'from-amber-950 via-slate-900 to-purple-950',
    difficulty: '⭐⭐⭐⭐ (高傲御姐与尊卑碾压)',
    tags: ['冷艳女王', '王座跪侍', '尊严剥夺', '10幕皇家戒律'],
    description: '宫殿高阶之上，冷艳女王赫莲娜翘着长腿端坐于王座。10 轮皇家戒律逐步降临...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '高耸的王座之下，赫莲娜女王手持银色权杖，居高临下地俯视着台阶下的你。',
        dialogue: '凡人，见到本王竟敢直视？还不立刻跪下领受皇家戒律！',
        choices: [
          {
            id: 'c1_kneel',
            text: '（俯首跪倒在台阶下）女王陛下万岁... 仆人向您致敬...',
            attitude: 'submissive',
            replyDialogue: '准你觐见。赐初阶皇家诫流！',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '微电流如银针般刺痛着你的肌肤，女王轻轻勾动手指。',
        dialogue: '第一诫：剥夺尊严。戴上纯金口塞与电流锁，在王座前膝行三步！',
        choices: [
          {
            id: 'c2_crawl',
            text: '（膝行上前，低头亲吻台阶）',
            attitude: 'submissive',
            replyDialogue: '爬行的姿态还算恭敬。开启慢速律动！',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 20 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '女王用权杖挑起你的下巴，另一只手按下了电击按钮。',
        dialogue: '第二诫：绝对忍耐。本王的权杖点在哪里，你的电流就会刺向哪里！',
        choices: [
          {
            id: 'c3_endure',
            text: '（紧咬口塞，强忍电击痛楚）',
            attitude: 'submissive',
            replyDialogue: '很好，忍耐力尚可。加大马达转速！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 20 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '下半身器械的抽送越来越剧烈，女王将权杖顶在你的胸口。',
        dialogue: '第三诫：认主誓言。说出你唯一的信仰！',
        choices: [
          {
            id: 'c4_swear',
            text: '（呜咽大喊）赫莲娜女王是我的唯一主宰！',
            attitude: 'submissive',
            replyDialogue: '赏你的！锯齿波形加压！',
            hardwareAction: { type: 'ems_wave', target: 'sawtooth_climb', durationSec: 20 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '狂暴的快感冲击着你的理智，就在你快要忍不住的瞬间，女王冷酷地收手断电！',
        dialogue: '（0.05秒急刹断电）第四诫：未经本王恩准，擅自高潮即为大逆不道！给我忍住！',
        choices: [
          {
            id: 'c5_beg_queen',
            text: '（双手合十哀求）求女王陛下赐予恩典...',
            attitude: 'begging',
            replyDialogue: '下奴安敢求饶？罚冷场 15 秒！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_6',
          },
        ],
      },
      step_6: {
        id: 'step_6',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '冷场 15 秒过后，女王重新启动了双通道电击，并拉到了 16 档。',
        dialogue: '第五诫：奉献一切。今晚你的整具躯体都将成为本王的王座基石！',
        choices: [
          {
            id: 'c6_total_devote',
            text: '（以头触地，全身颤抖受刑）仆人愿为陛下奉献一切！',
            attitude: 'submissive',
            replyDialogue: '开启 18 档超频轰鸣！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_18', durationSec: 20 },
            nextStepId: 'step_7',
          },
        ],
      },
      step_7: {
        id: 'step_7',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '10 道皇家戒律已经考验过半，女王走下王座，用鞋尖轻轻踩在你的手背上。',
        dialogue: '第六诫：永恒烙印。亲吻鞋尖，承认你永生永世是本王的奴隶！',
        choices: [
          {
            id: 'c7_kiss_heel',
            text: '（虔诚亲吻高跟鞋尖）我永远是陛下的奴隶...',
            attitude: 'submissive',
            replyDialogue: '准许进入终极大赏赐程序！',
            hardwareAction: { type: 'toy_pattern', target: 'deep_pulse', durationSec: 25 },
            nextStepId: 'step_8',
          },
        ],
      },
      step_8: {
        id: 'step_8',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '女王回到了王座，解开了你身上的最后一层禁锢。',
        dialogue: '第七诫：领受皇恩。现在，以赫莲娜女王之名，恩赐你终极高潮！',
        choices: [
          {
            id: 'c8_climax_call',
            text: '（泪流满面，大声谢恩）谢女王陛下隆恩！！',
            attitude: 'submissive',
            replyDialogue: '终极大招——全速 20 档超频榨干！！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'step_9',
          },
        ],
      },
      step_9: {
        id: 'step_9',
        speaker: '冷艳女王 赫莲娜',
        avatar: '👑',
        narrative: '【第 10 幕 · 王者终极极乐恩赏】20 档超频与电击狂暴交织，在长达 30 秒的极乐痉挛中将你彻底推向神魂颠倒的巅峰！',
        dialogue: '（高坐王座微笑）表现得很好。今后，王座下的这块软垫就是你的专属位置。',
        choices: [
          {
            id: 'c9_queen_ending',
            text: '（瘫软在台阶上，幸福地成为女王王座下的专属跪奴）',
            attitude: 'submissive',
            replyDialogue: '好好服侍本王，少不了你的赏赐。',
            hardwareAction: { type: 'toy_pattern', target: 'breathe', durationSec: 20 },
            nextStepId: 'ending',
            endingTitle: '👑 结局：女王王座下的永恒侍臣',
            endingDesc: '你通过了赫莲娜女王 10 道严酷而威严的皇家戒律考验，尊严彻底被折服，成为女王王座之下最忠诚、最受宠爱的专属侍从。',
            endingType: 'surrender',
          },
        ],
      },
    },
  },

  // 剧本 8: 《深海潜艇密封舱的憋胀极限》 (长篇 3000 字)
  {
    id: 'dom_submarine_enema',
    title: '深海潜艇密封舱的憋胀极限',
    subtitle: '深潜千米水下，严苛大副用 10 轮高压灌注考验你的耐压意志...',
    category: '经典硬核支配',
    isFemboy: false,
    avatar: '🌊',
    bgGradient: 'from-blue-950 via-slate-900 to-cyan-950',
    difficulty: '⭐⭐⭐⭐⭐ (水压憋胀极限)',
    tags: ['深海潜艇', '密封舱', '高压灌注', '憋水特训', '10幕深海小说'],
    description: '深海千米潜艇密闭舱内，严厉的大副锁死阀门。10 轮高压海水灌注特训逐步加压...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '潜艇大副 雷蒙德',
        avatar: '🌊',
        narrative: '金属密封舱门缓缓闭合，舱内传来深海水压的低鸣。雷蒙德大副手持高压注水控制阀。',
        dialogue: '深海潜水特训第一条：身体必须具备极强的水压耐受力！插上高压注水管，准备迎接 10 轮水压冲击！',
        choices: [
          {
            id: 'c1_agree',
            text: '（接上注水管）报告大副，已准备完毕！',
            attitude: 'submissive',
            replyDialogue: '很好！先注入 100ml 预热水压！',
            hardwareAction: { type: 'enema_pattern', target: 'slow_fill', durationSec: 15 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '潜艇大副 雷蒙德',
        avatar: '🌊',
        narrative: '温水注入腹部，胀满感迅速蔓延。大副开启了微电流辅助收缩。',
        dialogue: '第二轮：括约肌耐压锁紧。开启微电流，不许漏出一滴水！',
        choices: [
          {
            id: 'c2_hold_tight',
            text: '（紧咬牙关死死收紧）报告大副，已死死锁住！',
            attitude: 'submissive',
            replyDialogue: '保持住！加压注入 150ml！',
            hardwareAction: { type: 'enema_pattern', target: 'medium_fill', durationSec: 20 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '潜艇大副 雷蒙德',
        avatar: '🌊',
        narrative: '腹部已经鼓起一个明显的弧度，水压传感器数值飙升到 80 hPa。',
        dialogue: '第三轮：深海震荡。启动体内震动棒，模拟千米水下的剧烈水流共振！',
        choices: [
          {
            id: 'c3_vibe_in',
            text: '（双手扶着舱壁发抖）肚子太涨了... 震得好剧烈...',
            attitude: 'begging',
            replyDialogue: '这就是深海的力量！给我挺住！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 20 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '潜艇大副 雷蒙德',
        avatar: '🌊',
        narrative: '剧烈的水波震荡与充盈感让你双腿发软，大副加上了双通道电击夹。',
        dialogue: '第四轮：全系统超载！电击与水压复合刺激！',
        choices: [
          {
            id: 'c4_endure_overload',
            text: '（大声吼叫忍受）啊啊啊——！！报告大副，还在坚持！！',
            attitude: 'submissive',
            replyDialogue: '像个真正的水兵！继续加压！',
            hardwareAction: { type: 'ems_wave', target: 'sawtooth_climb', durationSec: 20 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '潜艇大副 雷蒙德',
        avatar: '🌊',
        narrative: '快感与憋胀感同时冲到了顶点，大副突然按下了冷场急停！',
        dialogue: '（0.05秒急刹断电）第五轮：紧急气闸闭合！在极限边缘强行冷场 15 秒！',
        choices: [
          {
            id: 'c5_wait_calm',
            text: '（大汗淋漓大口喘息）呼... 呼... 遵命！',
            attitude: 'submissive',
            replyDialogue: '意志力极佳。即将进入第 10 轮终极大排水与喷发！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_6',
          },
        ],
      },
      step_6: {
        id: 'step_6',
        speaker: '潜艇大副 雷蒙德',
        avatar: '🌊',
        narrative: '【第 10 幕 · 深海终极高压释放】阀门彻底全开，20 档马达与全电击全速运转，所有的水压与前列腺快感同时狂暴喷射而出！',
        dialogue: '（大声下令）全员排水！迎接属于你的深海大解脱吧！！',
        choices: [
          {
            id: 'c6_submarine_ending',
            text: '（在极致的水流喷涌与狂暴高潮中彻底瘫软）',
            attitude: 'submissive',
            replyDialogue: '恭喜你，水兵！你通过了全部深海耐压考核！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'ending',
            endingTitle: '🌊 结局：深海潜艇的铁血水兵',
            endingDesc: '你顶住了 10 轮残酷的高压海水灌注与高潮急刹考验，肉体耐压意志被彻底激发，成为雷蒙德大副手下最坚韧有力的专属水兵。',
            endingType: 'conquer',
          },
        ],
      },
    },
  },

  // 剧本 9: 《感官剥夺与超频电击特训》 (长篇 3000 字)
  {
    id: 'dom_sensory_deprivation',
    title: '感官剥夺与超频电击特训',
    subtitle: '戴上全黑眼罩与降噪耳机，在绝对黑暗中承受 10 轮未知电击的狂暴洗礼...',
    category: '经典硬核支配',
    isFemboy: false,
    avatar: '👁️',
    bgGradient: 'from-zinc-950 via-slate-900 to-stone-950',
    difficulty: '⭐⭐⭐⭐⭐ (纯粹未知的恐惧与极乐)',
    tags: ['感官剥夺', '全黑眼罩', '未知电击', '10幕硬核小说'],
    description: '绝对静音的漆黑特训室，眼罩夺去了你的视线，耳机隔绝了所有声音。10 轮未知的电流将随机轰击你的身体...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '硬核特训教官 雷恩',
        avatar: '👁️',
        narrative: '全黑眼罩紧紧蒙住了你的双眼，降噪耳机里只有教官低沉的电子音。',
        dialogue: '菜鸟，失去视力和听力后，你的触觉会被放大十倍。准备好迎接 10 轮未知方位的电流轰炸了吗？',
        choices: [
          {
            id: 'c1_ready',
            text: '（深呼吸，在黑暗中点头）报告教官，准备就绪！',
            attitude: 'submissive',
            replyDialogue: '很好！第一击——未知方位微电流刺探！',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '硬核特训教官 雷恩',
        avatar: '👁️',
        narrative: '黑暗中没有任何预警，左侧腹肌突然传来一阵针扎般的电流跳变！',
        dialogue: '第二击！感受这种未知的恐惧吧！档位直接加压 20%！',
        choices: [
          {
            id: 'c2_endure_dark',
            text: '（倒吸一口凉气，肌肉紧绷）',
            attitude: 'submissive',
            replyDialogue: '不许乱动！保持立正姿势！',
            hardwareAction: { type: 'ems_wave', target: 'electric_comb', durationSec: 15 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '硬核特训教官 雷恩',
        avatar: '👁️',
        narrative: '黑暗中，下方的玩具器械突然无声启动，九浅一深直接深顶到最深处！',
        dialogue: '第三击！双通道感官夹击！在黑暗里大声数出每一次抽插！',
        choices: [
          {
            id: 'c3_count_loud',
            text: '（在黑暗中大声数数）一！二！三... 呃啊！',
            attitude: 'submissive',
            replyDialogue: '声音洪亮！锯齿波形加压！',
            hardwareAction: { type: 'ems_wave', target: 'sawtooth_climb', durationSec: 20 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '硬核特训教官 雷恩',
        avatar: '👁️',
        narrative: '没有任何视觉参考，每一秒的电击都如同雷霆降临，你的身体彻底沉沦在感官孤岛中。',
        dialogue: '第四击：狂暴雷暴测试！挺过这 20 秒，你就通过了一半的特训！',
        choices: [
          {
            id: 'c4_storm_endure',
            text: '（死死咬牙，在黑暗中狂乱颤抖）',
            attitude: 'submissive',
            replyDialogue: '硬汉！马达调速推至 18 档！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_18', durationSec: 20 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '硬核特训教官 雷恩',
        avatar: '👁️',
        narrative: '【第 10 幕 · 黑暗终极雷暴大释放】耳机里倒数三声，全功率 20 档超频与最大电击在绝对黑暗中瞬间爆发，整整 30 秒将你推上云端！',
        dialogue: '（耳机里传来威严的掌声）特训圆满结束！菜鸟，你证明了自己的钢铁意志！',
        choices: [
          {
            id: 'c5_deprivation_ending',
            text: '（摘下眼罩，在刺眼光芒与无尽余韵中瘫软喘息）',
            attitude: 'submissive',
            replyDialogue: '归队休息！',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'ending',
            endingTitle: '⚡ 结局：感官剥夺特训终极钢铁硬汉',
            endingDesc: '在绝对黑暗与静音中经受了 10 轮未知的电击与狂暴马达淬炼，你的感官神经彻底觉醒，成为特训营最坚不可摧的终极战士。',
            endingType: 'conquer',
          },
        ],
      },
    },
  },

  // 剧本 10: 《病娇青梅的锁心爱巢》 (长篇 3000 字)
  {
    id: 'dom_yandere_cage',
    title: '病娇青梅的锁心爱巢',
    subtitle: '被偏执青梅竹马锁在粉红地下室，10 句甜蜜致命的爱之箴言逼你彻底归她所有...',
    category: '经典硬核支配',
    isFemboy: false,
    avatar: '🔪',
    bgGradient: 'from-rose-950 via-slate-900 to-purple-950',
    difficulty: '⭐⭐⭐⭐ (病娇偏执与甜蜜占有)',
    tags: ['病娇少女', '地下室囚禁', '爱之锁链', '10幕病娇小说'],
    description: '挂满两人合照的粉色地下室，青梅竹马小雨微笑着锁上了防盗门。10 轮甜蜜又窒息的病态爱意逐步展开...',
    initialStepId: 'step_1',
    steps: {
      step_1: {
        id: 'step_1',
        speaker: '病娇青梅 小雨',
        avatar: '🔪',
        narrative: '地下室点满了心形蜡烛，小雨坐在床边，轻轻摇晃着一把粉色的小钥匙。',
        dialogue: '呐~ 终于只有我们两个人了呢。外面那些狐狸精再也见不到你了~ 乖乖躺好，戴上小雨亲手为你做的爱心项圈吧~',
        choices: [
          {
            id: 'c1_accept_yandere',
            text: '（顺从躺好）小雨... 我不会离开你的...',
            attitude: 'submissive',
            replyDialogue: '嘻嘻~我就知道你最爱小雨了！先给你尝尝小雨甜蜜的爱意电波~',
            hardwareAction: { type: 'ems_wave', target: 'sensory_tickle', durationSec: 10 },
            nextStepId: 'step_2',
          },
        ],
      },
      step_2: {
        id: 'step_2',
        speaker: '病娇青梅 小雨',
        avatar: '🔪',
        narrative: '微电流沿着小腹蔓延，小雨拿出了心形的感官器械，温柔地推进你的身体。',
        dialogue: '第 2 句爱之箴言：你的身体每分每秒都必须被小雨的爱意填满哦~ 启动 8 档慢速绞磨~',
        choices: [
          {
            id: 'c2_yandere_fill',
            text: '（被填满的充实感）好胀... 全是小雨的味道...',
            attitude: 'submissive',
            replyDialogue: '永远不要拔出来哦~ 启动心跳脉冲！',
            hardwareAction: { type: 'toy_pattern', target: 'slow_churn', durationSec: 20 },
            nextStepId: 'step_3',
          },
        ],
      },
      step_3: {
        id: 'step_3',
        speaker: '病娇青梅 小雨',
        avatar: '🔪',
        narrative: '小雨将水果刀插在床头木板上，眼神里满是病态的狂热爱恋。',
        dialogue: '第 3 句爱之箴言：昨天看你和别的女生多说了两句话，小雨的心好痛好痛呢... 作为惩罚，电击加倍！',
        choices: [
          {
            id: 'c3_yandere_punish',
            text: '（被电得浑身发抖大喊）对不起！我以后再也不看别人了！',
            attitude: 'begging',
            replyDialogue: '发誓的声音真好听~ 原谅你啦！马达调速推至九浅一深！',
            hardwareAction: { type: 'toy_pattern', target: 'nine_shallow_one_deep', durationSec: 20 },
            nextStepId: 'step_4',
          },
        ],
      },
      step_4: {
        id: 'step_4',
        speaker: '病娇青梅 小雨',
        avatar: '🔪',
        narrative: '快感疯狂堆积，就在你快要爆发的瞬间，小雨突然拔掉插头急停！',
        dialogue: '（0.05秒急刹断电）第 4 句爱之箴言：没有小雨的倒数，擅自高潮就是背叛小雨！给我憋回去！',
        choices: [
          {
            id: 'c4_beg_yandere',
            text: '（抓住床单哭泣）小雨... 我憋住了... 求你让我高潮吧...',
            attitude: 'begging',
            replyDialogue: '乖孩子，多憋一会儿，快感才会像小雨的爱一样浓烈嘛~ 冷场 15 秒！',
            hardwareAction: { type: 'stop', target: 'all', durationSec: 15 },
            nextStepId: 'step_5',
          },
        ],
      },
      step_5: {
        id: 'step_5',
        speaker: '病娇青梅 小雨',
        avatar: '🔪',
        narrative: '【第 10 幕 · 病娇终极永恒爱巢大释放】小雨扑在你的怀里，按下 20 档超频与暴风雨电击，在整整 30 秒的疯狂极乐中彻底将你占为己有！',
        dialogue: '（眼眶泛红热泪盈眶）射在小雨的怀里吧！从今往后，永生永世，你都是小雨一个人的人偶了~',
        choices: [
          {
            id: 'c5_yandere_ending',
            text: '（在窒息的病态爱意与疯狂绝顶中，彻底沉沦在爱巢中）',
            attitude: 'submissive',
            replyDialogue: '小雨永远爱你哦... 永远永远...',
            hardwareAction: { type: 'toy_turbo', target: 'turbo_20', durationSec: 30 },
            nextStepId: 'ending',
            endingTitle: '🔪 结局：病娇爱巢中的永恒爱之囚徒',
            endingDesc: '你彻底放弃了逃离的念头，在小雨 10 轮病态又炽热的爱意拷问与极限榨干下，永远留在了这间充满甜蜜与疯狂的地下室中。',
            endingType: 'surrender',
          },
        ],
      },
    },
  },
];

export const DUNGEON_SCRIPTS: DungeonScript[] = [
  ...EXTRA_FEMBOY_DUNGEONS,
  ...BASE_DUNGEON_SCRIPTS,
];
