import React, { useEffect, useState } from 'react';
import { LocalAsmrTrack, LocalAsmrCategory, listLocalAsmrTracks, updateLocalAsmrTracks, deleteLocalAsmrTrack, renameLocalAsmrTrack } from '../../core/asmr/localAudioLibrary';
export function AudioLibraryManager({ tracks, categories, categoryId, queueIds, onQueue, onChange, onPlay, onStop }: { tracks: LocalAsmrTrack[]; categories: LocalAsmrCategory[]; categoryId: string; queueIds: string[]; onQueue: (ids: string[]) => void; onChange: () => Promise<void>; onPlay: (track: LocalAsmrTrack) => void; onStop: () => void }) {
  const [all, setAll] = useState<LocalAsmrTrack[]>([]), [query, setQuery] = useState(''), [scope, setScope] = useState('category'), [sort, setSort] = useState('newest'), [selected, setSelected] = useState<string[]>([]), [busy, setBusy] = useState(false), [notice, setNotice] = useState('');
  useEffect(() => { let mounted = true; void listLocalAsmrTracks(true).then(data => { if (mounted) setAll(data); }).catch(e => { if (mounted) setNotice(String(e)); }); return () => { mounted = false; }; }, [tracks]);
  useEffect(() => setSelected([]), [scope, categoryId, query]);
  const act = async (work: () => Promise<unknown>) => { if (busy) return; setBusy(true); try { await work(); await onChange(); setAll(await listLocalAsmrTracks(true)); setSelected([]); setNotice('操作已保存'); } catch (e) { setNotice(e instanceof Error ? e.message : '操作失败'); } finally { setBusy(false); } };
  const visible = all.filter(t => scope === 'trash' ? !!t.deletedAt : !t.deletedAt && (scope === 'all' || scope === 'favorites' && t.favorite || scope === 'queue' && queueIds.includes(t.id) || scope === 'category' && t.categoryId === categoryId)).filter(t => `${t.title} ${t.fileName}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => scope === 'queue' ? queueIds.indexOf(a.id) - queueIds.indexOf(b.id) : sort === 'name' ? a.title.localeCompare(b.title, 'zh-CN') : sort === 'size' ? b.size - a.size : b.createdAt - a.createdAt);
  const recycle = (ids: string[]) => { if (!confirm(`将 ${ids.length} 个音频移入回收站？文件仍占用空间，可以恢复。`)) return; onStop(); void act(() => updateLocalAsmrTracks(ids, { deletedAt: Date.now() })); };
  return <section className="ui-card m-3 space-y-3"><h3 className="font-bold">音频管理</h3><input className="w-full p-2 text-xs" aria-label="搜索音频" placeholder="搜索名称或文件名" value={query} onChange={e => setQuery(e.target.value)} /><div className="grid grid-cols-2 gap-2 text-xs"><select aria-label="音频范围" className="p-2" value={scope} onChange={e => setScope(e.target.value)}><option value="category">当前分类</option><option value="all">全部音频</option><option value="favorites">收藏</option><option value="queue">我的播放列表</option><option value="trash">回收站</option></select><select aria-label="音频排序" className="p-2" value={sort} onChange={e => setSort(e.target.value)} disabled={scope === 'queue'}><option value="newest">最新导入</option><option value="name">名称</option><option value="size">文件大小</option></select></div>
    <label className="text-xs flex gap-2"><input type="checkbox" disabled={busy || !visible.length} checked={!!visible.length && visible.every(t => selected.includes(t.id))} onChange={e => setSelected(e.target.checked ? visible.map(t => t.id) : [])} />选择当前结果（{selected.length}）</label>
    {selected.length > 0 && <div className="flex flex-wrap gap-2">{scope === 'trash' ? <button disabled={busy} className="ui-button-secondary" onClick={() => void act(() => updateLocalAsmrTracks(selected, { deletedAt: 0 }))}>批量恢复</button> : <><select aria-label="批量移动到分类" className="p-2 text-xs" disabled={busy} value="" onChange={e => void act(() => updateLocalAsmrTracks(selected, { categoryId: e.target.value }))}><option value="" disabled>批量移动到…</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><button disabled={busy} className="ui-button-secondary" onClick={() => onQueue([...new Set([...queueIds, ...selected])].slice(0, 200))}>加入播放列表</button><button disabled={busy} className="ui-button-secondary" onClick={() => recycle(selected)}>移入回收站</button></>}</div>}
    {scope === 'queue' && <p className="ui-muted text-xs">按加入顺序跨分类播放，可用箭头调整。播放列表有内容时，播放器优先使用它。</p>}
    <div className="max-h-96 overflow-y-auto space-y-3">{visible.map(t => <div key={t.id} className="border-t border-[var(--line)] pt-3 space-y-2"><div className="flex gap-2"><input type="checkbox" aria-label={`选择 ${t.title}`} disabled={busy} checked={selected.includes(t.id)} onChange={e => setSelected(e.target.checked ? [...selected, t.id] : selected.filter(id => id !== t.id))} /><strong className="text-xs break-words">{t.title}</strong></div><p className="ui-muted text-xs break-all">{(t.size / 1048576).toFixed(1)} MB · {t.fileName}</p><div className="flex gap-2 flex-wrap">{t.deletedAt ? <><button disabled={busy} className="ui-button-secondary" onClick={() => void act(() => updateLocalAsmrTracks([t.id], { deletedAt: 0 }))}>恢复</button><button disabled={busy} className="ui-button-secondary" onClick={() => { if (confirm(`彻底删除“${t.title}”？音频文件无法找回。`)) void act(async () => { await deleteLocalAsmrTrack(t.id); onQueue(queueIds.filter(id => id !== t.id)); }); }}>彻底删除</button></> : <><button disabled={busy} className="ui-button-secondary" onClick={() => onPlay(t)}>播放 / 暂停</button><button disabled={busy} className="ui-button-secondary" onClick={() => void act(() => updateLocalAsmrTracks([t.id], { favorite: !t.favorite }))}>{t.favorite ? '取消收藏' : '收藏'}</button><button disabled={busy} className="ui-button-secondary" onClick={() => { const title = prompt('音频名称', t.title); if (title?.trim()) void act(() => renameLocalAsmrTrack(t, title)); }}>改名</button><button disabled={busy} className="ui-button-secondary" onClick={() => onQueue(queueIds.includes(t.id) ? queueIds.filter(id => id !== t.id) : [...queueIds, t.id])}>{queueIds.includes(t.id) ? '移出列表' : '加入列表'}</button><button disabled={busy} className="ui-button-secondary" onClick={() => recycle([t.id])}>删除</button>{scope === 'queue' && [-1, 1].map(offset => <button key={offset} className="ui-button-secondary" disabled={busy || queueIds.indexOf(t.id) + offset < 0 || queueIds.indexOf(t.id) + offset >= queueIds.length} onClick={() => { const next = [...queueIds], index = next.indexOf(t.id); [next[index], next[index + offset]] = [next[index + offset], next[index]]; onQueue(next); }}>{offset < 0 ? '上移' : '下移'}</button>)}</>}</div></div>)}</div>
    {!visible.length && <p className="ui-muted text-xs">这里还没有音频，或没有符合搜索条件的结果。</p>}{notice && <p role="status" className="ui-muted text-xs">{notice}</p>}
  </section>;
}
