import React, { useEffect, useRef, useState } from 'react';
import { WardrobeEngine, WardrobeState, WARDROBE_ITEMS } from '../../core/wardrobe/wardrobeData';
import { PersonalItem, WardrobeLook, WARDROBE_PLACEHOLDER } from '../../core/wardrobe/personalWardrobe';
const categories = { casual: '日常', dress: '裙装', accessory: '配饰', formal: '正式', traditional: '传统', cosplay: '角色装', maid: '女仆', lingerie: '贴身', toy: '用品' };
export function PersonalWardrobePanel({ engine, state, onChange, onDiary, readPhoto }: { engine: WardrobeEngine; state: WardrobeState; onChange: () => void; onDiary: (id: string) => void; readPhoto: (file: File) => Promise<string> }) {
  const [view, setView] = useState('personal'), [query, setQuery] = useState(''), [notice, setNotice] = useState(''), [reading, setReading] = useState(false);
  const [item, setItem] = useState<Partial<PersonalItem> | null>(null), [look, setLook] = useState<Partial<WardrobeLook> | null>(null);
  const photoRequest = useRef(0); useEffect(() => () => { photoRequest.current++; }, []);
  const run = (work: () => void) => { try { work(); onChange(); setNotice('已保存到个人衣橱'); return true; } catch (e) { setNotice(e instanceof Error ? e.message : '保存失败'); return false; } };
  const list = [...WARDROBE_ITEMS, ...state.customItems].filter(i => view === 'archive' ? 'archived' in i && i.archived : !('archived' in i && i.archived)).filter(i => look || view === 'all' || view === 'archive' || view === 'wanted' && state.ownership[i.id] === 'wanted' || view === 'personal' && (i.id.startsWith('personal-') || state.ownership[i.id] === 'owned')).filter(i => `${i.name} ${i.description}`.toLowerCase().includes(query.toLowerCase()));
  const editItem = (next: Partial<PersonalItem> | null) => { photoRequest.current++; setReading(false); setItem(next); };
  return <section className="ui-card space-y-3"><h3 className="font-bold">个人衣橱与搭配</h3><p className="ui-muted text-xs">照片仅在本机压缩保存，不上传。最多 30 件个人物品、50 套搭配（含归档）；归档保留旧日记关联，也可恢复。</p><div className="flex flex-wrap gap-2"><button className="ui-button" onClick={() => editItem({ name: '', category: 'casual', image: '', description: '' })}>添加物品</button><button className="ui-button-secondary" onClick={() => { setLook({ name: '', itemIds: [] }); setView('all'); }}>组合搭配</button></div>
    {item && <div className="rounded-xl border border-[var(--line)] p-3 space-y-2"><label className="text-xs block">物品名称<input className="w-full p-2" value={item.name || ''} maxLength={80} onChange={e => setItem({ ...item, name: e.target.value })} /></label><select aria-label="个人物品分类" value={item.category} className="w-full p-2 text-xs" onChange={e => setItem({ ...item, category: e.target.value as PersonalItem['category'] })}>{Object.entries(categories).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select><textarea aria-label="个人物品备注" placeholder="尺码、颜色、面料或备注" className="w-full p-2 text-xs" maxLength={500} value={item.description || ''} onChange={e => setItem({ ...item, description: e.target.value })} />{item.image && <img src={item.image} alt="个人物品预览" className="w-full h-36 object-contain rounded-xl" />}<label className="block text-xs">上传物品照片<input type="file" accept="image/jpeg,image/png,image/webp" disabled={reading} className="w-full mt-1" onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; const request = ++photoRequest.current; setReading(true); void readPhoto(file).then(image => { if (request === photoRequest.current) setItem(current => current ? { ...current, image } : null); }).catch(error => { if (request === photoRequest.current) setNotice(String(error)); }).finally(() => { if (request === photoRequest.current) setReading(false); }); }} /></label><div className="flex gap-2"><button disabled={reading} className="ui-button" onClick={() => { if (run(() => engine.savePersonalItem({ ...item, name: item.name || '' }))) editItem(null); }}>{reading ? '正在压缩…' : '保存物品'}</button><button className="ui-button-secondary" onClick={() => editItem(null)}>取消</button><button className="ui-button-secondary" disabled={reading} onClick={() => setItem({ ...item, image: '' })}>移除照片</button></div></div>}
    {look && <div className="rounded-xl border border-[var(--line)] p-3 space-y-2"><input aria-label="搭配名称" placeholder="给这套搭配起个名字" className="w-full p-2 text-xs" maxLength={80} value={look.name || ''} onChange={e => setLook({ ...look, name: e.target.value })} /><p className="ui-muted text-xs">在下方勾选 1–12 件物品，已选 {look.itemIds?.length || 0} 件。</p><div className="flex gap-2"><button className="ui-button" onClick={() => { if (run(() => engine.saveLook({ ...look, name: look.name || '', itemIds: look.itemIds || [] }))) setLook(null); }}>保存搭配</button><button className="ui-button-secondary" onClick={() => setLook(null)}>取消</button></div></div>}
    <div className="flex gap-2"><input aria-label="搜索衣橱物品" className="w-full min-w-0 p-2 text-xs" placeholder="搜索物品名称或备注" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="个人衣橱范围" className="p-2 text-xs" value={view} onChange={e => setView(e.target.value)}><option value="personal">我的物品</option><option value="wanted">想入手</option><option value="all">全部物品</option><option value="archive">已归档</option></select></div>
    <div className="grid grid-cols-2 gap-2 max-h-[32rem] overflow-y-auto">{list.map(i => <article key={i.id} className="rounded-xl border border-[var(--line)] overflow-hidden"><img src={i.image || WARDROBE_PLACEHOLDER} alt={i.name} loading="lazy" className="h-28 w-full object-contain bg-[#fff8fa]" /><div className="p-2 space-y-2"><strong className="block text-xs break-words">{i.name}</strong>{look && <label className="text-xs flex gap-1"><input type="checkbox" checked={look.itemIds?.includes(i.id) || false} disabled={!look.itemIds?.includes(i.id) && (look.itemIds?.length || 0) >= 12} onChange={e => setLook({ ...look, itemIds: e.target.checked ? [...(look.itemIds || []), i.id] : look.itemIds?.filter(id => id !== i.id) })} />加入此搭配</label>}<select aria-label={`${i.name}拥有状态`} className="w-full p-1 text-xs" value={state.ownership[i.id] || ''} onChange={e => run(() => engine.setOwnership(i.id, e.target.value as 'owned' | 'wanted' | ''))}><option value="">未标记</option><option value="owned">已拥有</option><option value="wanted">想入手</option></select><div className="flex gap-1 flex-wrap">{'archived' in i && i.archived ? <button className="ui-button-secondary" onClick={() => run(() => engine.savePersonalItem({ ...i, archived: false }))}>恢复</button> : <button className="ui-button-secondary" onClick={() => onDiary(i.id)}>写日记</button>}{i.id.startsWith('personal-') && <><button className="ui-button-secondary" onClick={() => editItem(i)}>编辑</button>{!('archived' in i && i.archived) && <button className="ui-button-secondary" onClick={() => { if (confirm('归档此物品？旧日记会保留，之后可恢复。')) run(() => engine.savePersonalItem({ ...i, archived: true })); }}>归档</button>}</>}</div></div></article>)}</div>{!list.length && <p className="ui-muted text-xs">还没有符合条件的物品。可以添加自己的照片，或从全部物品中标记“已拥有”。</p>}
    <details><summary className="font-bold text-xs cursor-pointer">我的搭配（{state.looks.length}）</summary><div className="space-y-3 mt-2">{state.looks.map(l => <div key={l.id} className="border-t border-[var(--line)] pt-2 space-y-1"><strong className="text-xs">{l.name}{l.archived ? '（已归档）' : ''}</strong><p className="ui-muted text-xs">{l.itemIds.map(id => [...WARDROBE_ITEMS, ...state.customItems].find(i => i.id === id)?.name || '未知物品').join(' + ')}</p><div className="flex gap-2 flex-wrap">{!l.archived && <button className="ui-button-secondary" onClick={() => onDiary(l.id)}>记录这套搭配</button>}<button className="ui-button-secondary" onClick={() => { setLook({ ...l, itemIds: [...l.itemIds] }); setView('all'); }}>编辑</button><button className="ui-button-secondary" onClick={() => run(() => engine.saveLook({ ...l, archived: !l.archived }))}>{l.archived ? '恢复' : '归档'}</button></div></div>)}</div></details>
    {notice && <p role="status" className="ui-muted text-xs">{notice}</p>}
  </section>;
}
