import React, { useState } from 'react';
import { SavedAsmrScript, saveAsmrScript, removeSavedScript } from '../../core/asmr/savedScripts';
export function SavedAsmrScripts({ tracks, onChange, onPlay }: { tracks: SavedAsmrScript[]; onChange: (tracks: SavedAsmrScript[]) => void; onPlay: (track: SavedAsmrScript) => void }) {
  const [editing, setEditing] = useState<SavedAsmrScript | null>(null);
  const [query, setQuery] = useState('');
  const [notice, setNotice] = useState('');
  return <section className="ui-card space-y-3"><h3 className="font-bold">我的 ASMR 剧本 · {tracks.length}</h3><p className="ui-muted text-xs">生成后自动保存在本机，播放需手动开启。自建剧本不启动硬件。</p>
    <input aria-label="搜索我的剧本" placeholder="搜索名称或分类" value={query} onChange={e => setQuery(e.target.value)} className="w-full p-2 text-xs" />
    {!tracks.length && <p className="ui-muted text-xs">生成的剧本会保存在这里。</p>}
    {tracks.filter(t => `${t.title} ${t.category}`.toLowerCase().includes(query.toLowerCase())).map(t => <div key={t.id} className="border-t border-[var(--line)] pt-3 space-y-2"><strong className="text-sm break-words">{t.title}</strong><p className="ui-muted text-xs">{t.category} · {t.durationMinutes} 分钟 · {t.whisperLines.length} 句</p><div className="flex gap-2"><button className="ui-button-secondary" onClick={() => onPlay(t)}>播放</button><button className="ui-button-secondary" onClick={() => setEditing({ ...t })}>编辑</button><button className="ui-button-secondary" onClick={() => { if (!confirm(`删除剧本“${t.title}”？建议先备份，此操作不能撤销。`)) return; try { onChange(removeSavedScript(t.id)); } catch (e) { setNotice(String(e)); } }}>删除</button></div></div>)}
    {editing && <div className="border border-[var(--line)] rounded-xl p-3 space-y-2"><label className="block text-xs">名称<input className="w-full p-2" value={editing.title} maxLength={100} onChange={e => setEditing({ ...editing, title: e.target.value })} /></label><label className="block text-xs">分类<input className="w-full p-2" value={editing.category} maxLength={30} onChange={e => setEditing({ ...editing, category: e.target.value })} /></label><label className="block text-xs">正文（每行一句，最多 30 句，每句 500 字）<textarea className="w-full p-2" rows={6} maxLength={15030} value={editing.whisperLines.join('\n')} onChange={e => setEditing({ ...editing, whisperLines: e.target.value.split('\n') })} /></label><label className="block text-xs">时长（分钟）<input type="number" min={1} max={60} value={editing.durationMinutes} onChange={e => setEditing({ ...editing, durationMinutes: Number(e.target.value) })} className="w-full p-2" /></label><div className="flex gap-2"><button className="ui-button" onClick={() => { try { if (!editing.title.trim() || editing.whisperLines.length > 30 || editing.whisperLines.some(line => line.length > 500)) throw new Error('请填写名称，并检查正文长度'); onChange(saveAsmrScript(editing)); setEditing(null); setNotice('已保存'); } catch (e) { setNotice(String(e)); } }}>保存</button><button className="ui-button-secondary" onClick={() => setEditing(null)}>取消</button></div></div>}
    {notice && <p role="status" className="ui-muted text-xs">{notice}</p>}
  </section>;
}
