import React, { useEffect, useState } from 'react';
import { getWeekProgress, loadWeeklyPlan, saveWeeklyPlan, WeeklyPlan, PlanTask } from '../../core/discipline/weeklyPlan';
import type { BarbieSuiteState } from '../../core/discipline/barbieSuiteState';
export function WeeklyTrainingPlan({ state, onOpen }: { state: BarbieSuiteState; onOpen: (tab: 'pitch' | 'posture') => void }) {
  const [plan, setPlan] = useState(loadWeeklyPlan), [editing, setEditing] = useState(false), [draft, setDraft] = useState<WeeklyPlan>(plan), [notice, setNotice] = useState(''), [now, setNow] = useState(new Date());
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 30000); return () => clearInterval(timer); }, []);
  const progress = getWeekProgress(plan, state, now), today = progress.find(day => day.today)!;
  const labels = { rest: '休息日', voice: '声线练习', posture: '姿态练习' };
  const apply = (value: WeeklyPlan) => { try { setPlan(saveWeeklyPlan(value)); setEditing(false); setNotice('计划已保存，按每周重复执行；不会自动开启训练或硬件。'); } catch (e) { setNotice(String(e)); } };
  return <section className="ui-card my-3 space-y-3"><div className="flex justify-between gap-2"><h3 className="font-bold text-sm">我的训练周计划</h3><button className="ui-button-secondary" onClick={() => { setDraft({ ...plan, days: plan.days.map(d => ({ ...d })) }); setEditing(value => !value); }}>调整计划</button></div><p className="ui-muted text-xs">{plan.paused ? '计划已暂停，可先安排练习与休息日。' : `今天：${labels[today.task]}${today.task !== 'rest' ? ` · ${today.completed}/${today.sessions} 次已保存训练` : ''}`}</p><div className="grid grid-cols-7 gap-1 text-center text-[10px]">{progress.map((d, i) => <div key={d.key} className={`rounded-lg p-1.5 ${d.today ? 'bg-pink-50 ring-1 ring-pink-300' : 'bg-slate-50'}`}><strong>{['一', '二', '三', '四', '五', '六', '日'][i]}</strong><p className="mt-1">{d.task === 'rest' ? '休息' : d.task === 'voice' ? '声线' : '姿态'}</p><p>{d.task === 'rest' ? '—' : `${d.completed}/${d.sessions}`}</p></div>)}</div><p className="ui-muted text-xs">按本地日期读取有效训练记录；不额外发放积分。修改计划不会删除记录。已保存记录有限，较早的完成情况可能无法统计。</p><div className="flex gap-2"><button className="ui-button-secondary" onClick={() => apply({ ...plan, paused: !plan.paused })}>{plan.paused ? '启用计划' : '暂停计划'}</button>{!plan.paused && today.task !== 'rest' && <button className="ui-button" onClick={() => onOpen(today.task === 'voice' ? 'pitch' : 'posture')}>前往今日练习</button>}</div>
    {editing && <div className="border-t border-[var(--line)] pt-3 space-y-2">{draft.days.map((d, i) => <div key={i} className="flex items-center gap-2 text-xs"><span>周{['一', '二', '三', '四', '五', '六', '日'][i]}</span><select aria-label={`周${i + 1}练习`} className="p-2 flex-1 min-w-0" value={d.task} onChange={e => setDraft({ ...draft, days: draft.days.map((day, index) => index === i ? { ...day, task: e.target.value as PlanTask } : day) })}>{Object.entries(labels).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select><select aria-label={`周${i + 1}目标次数`} className="p-2" disabled={d.task === 'rest'} value={d.sessions} onChange={e => setDraft({ ...draft, days: draft.days.map((day, index) => index === i ? { ...day, sessions: Number(e.target.value) } : day) })}>{[1, 2, 3, 4, 5].map(n => <option value={n} key={n}>{n} 次</option>)}</select></div>)}<div className="flex gap-2"><button className="ui-button" onClick={() => apply(draft)}>保存安排</button><button className="ui-button-secondary" onClick={() => setEditing(false)}>取消</button></div></div>}{notice && <p role="status" className="ui-muted text-xs">{notice}</p>}
  </section>;
}
