import { TrainingTask } from '../../types';

export const FEMBOY_STAGE_GUIDES = {
  1: { title: '自我观察与舒适起步', objective: '建立安全词、呼吸、声线与个人风格基线。', unlockText: '完成任意 4 项后解锁 Stage 2', required: 4 },
  2: { title: '仪态与表达训练', objective: '练习步态、镜头表现、礼仪表达与合作反馈。', unlockText: '完成任意 4 项后解锁 Stage 3', required: 4 },
  3: { title: '感官辨识与节奏自主', objective: '识别身体信号，学会主动调节节奏和选择剧情分支。', unlockText: '完成任意 4 项后解锁 Stage 4', required: 4 },
  4: { title: '综合创作与长期计划', objective: '把声线、仪态、造型和叙事整合为可持续作品。', unlockText: '完成任意 4 项获得阶段毕业标记', required: 4 },
} as const;

export const FEMBOY_TRAINING_TASKS: TrainingTask[] = [
  // ==========================================
  // Stage 1: 羞耻脱敏与认知打破 (Cognitive & Shameless Desensitization)
  // ==========================================
  {
    id: 's1_mirror_shame',
    stage: 1,
    title: '镜前自省与认知脱敏',
    subtitle: '直面镜中的自己，打碎坚硬的男性外壳',
    durationMinutes: 5,
    mentorPersonaId: 'dark_femboy',
    icon: '🪞',
    clothingRequirement: '卸下束缚，仅着轻薄衣物',
    postureRequirement: '跪坐于全身镜前，双手置于大腿内侧',
    description: '在低频微电流的轻抚下，注视镜中自己逐渐泛红的眼角与呼吸，承认内心对娇柔快感的渴望。',
    hardwareConfig: {
      emsWave: 'sensory_tickle',
      emsStrengthA: 18,
      emsStrengthB: 18,
      toyPattern: 'gentle_wave',
      toyMotorRate: 3,
    },
    mentorVoiceIntro: '乖乖跪在镜子前看着自己哦。别再抗拒了，听听微电流在身体里游走的声音，小男娘的第一步就是学会享受羞耻呢~',
    mentorVoiceOutro: '表现得很乖哦~ 看着镜子里喘息的你，是不是已经感觉身心都变得软绵绵了？第一课顺利完成！',
  },
  {
    id: 's1_silk_touch',
    stage: 1,
    title: '丝袜触感与感官重构',
    subtitle: '让光滑的丝绸与微流唤醒皮肤的每一寸敏感',
    durationMinutes: 8,
    mentorPersonaId: 'dark_femboy',
    icon: '🩰',
    clothingRequirement: '穿戴连裤丝袜或过膝长筒白丝',
    postureRequirement: '平躺或靠坐，双腿微微并拢曲起',
    description: '丝袜轻柔摩擦大腿皮肤，配合慢速呼吸波形，重新建立全身皮肤对娇嫩与敏感的记忆。',
    hardwareConfig: {
      emsWave: 'breathe',
      emsStrengthA: 24,
      emsStrengthB: 24,
      toyPattern: 'breathe_pulse',
      toyMotorRate: 5,
    },
    mentorVoiceIntro: '穿好丝袜了吗？感受丝织物贴着大腿的滑腻感吧，加上我的微电流刺激，你的防线很快就会融化掉哦~',
    mentorVoiceOutro: '丝袜裹着双腿的感觉很棒吧？从今天起，你的身体已经习惯这种娇软的触感了呢~',
  },
  {
    id: 's1_succubus_breath',
    stage: 1,
    title: '魅魔浅吻与呼吸调同',
    subtitle: '跟随恶魔节拍，将急促的喘息转化为甜腻娇喘',
    durationMinutes: 10,
    mentorPersonaId: 'succubus_lilith',
    icon: '😈',
    clothingRequirement: '穿戴猫耳或兔耳发箍',
    postureRequirement: '侧卧放松，双手抱紧软枕',
    description: '莉莉丝导师以媚药微流循序渐进地注入神经，引导你放下紧绷的喉咙，发出娇柔顺从的呼吸。',
    hardwareConfig: {
      emsWave: 'numbing_buzz',
      emsStrengthA: 28,
      emsStrengthB: 28,
      toyPattern: 'warmup_crescendo',
      toyMotorRate: 6,
    },
    mentorVoiceIntro: '呼~ 莉莉丝老师来给你调音了哦。不要憋着声音，跟着电波的节拍，把心里最酸软的声音喘出来给我听~',
    mentorVoiceOutro: '刚才的声音真是太甜了~ 老师对你的表现非常满意，你很有当魅魔特等侍从的天赋呢！',
  },
  {
    id: 's1_nun_cleansing',
    stage: 1,
    title: '圣洁洗礼与凡欲剥夺',
    subtitle: '索菲亚修女的圣水慢灌与凡俗戒律',
    durationMinutes: 10,
    mentorPersonaId: 'cyber_nun_sophia',
    icon: '⛪',
    clothingRequirement: '纯白长衫或修女头巾',
    postureRequirement: '双膝跪于圣毯上，脊背挺直，双手合十',
    description: '在圣律微电流与温水充盈的双重压迫下，进行虔诚的静心忏悔，洗刷肉体深处的狂躁与抗拒。',
    hardwareConfig: {
      emsWave: 'pinch_crescendo',
      emsStrengthA: 32,
      emsStrengthB: 32,
      toyPattern: 'slow_churn',
      toyMotorRate: 6,
    },
    mentorVoiceIntro: '以圣光之名，洗涤你的凡俗傲慢。合上双眼，在圣律雷霆的微光中洗清一切杂念。',
    mentorVoiceOutro: '很好，你的心跳与神经已渐渐趋于纯净。圣坛认可了你第一阶段的洗礼。',
  },

  // ==========================================
  // Stage 2: 蕾丝体态与女仆规矩 (Lace Posture & Maid Invariants)
  // ==========================================
  {
    id: 's2_maid_kneeling',
    stage: 2,
    title: '女仆端庄跪侍考核',
    subtitle: '克莱尔大小姐的 10 分钟跪侍体态规矩',
    durationMinutes: 10,
    mentorPersonaId: 'lady_claire',
    icon: '🎀',
    clothingRequirement: '女仆围裙与蕾丝花边发带',
    postureRequirement: '双膝跪地，大腿并拢，腰背挺直，双手平端托盘/手机',
    description: '在金属感官塞与脉冲刺激下保持标准女仆跪姿，身体不可有丝毫晃动与懈怠。',
    hardwareConfig: {
      emsWave: 'sawtooth_climb',
      emsStrengthA: 35,
      emsStrengthB: 35,
      toyPattern: 'suction_grip',
      toyMotorRate: 8,
    },
    mentorVoiceIntro: '女仆就要有女仆的规矩！把背挺直，双腿夹紧！敢晃动一下，本小姐立刻给你加倍电击惩罚！',
    mentorVoiceOutro: '哼，算你识相，跪得还挺周正。赏你一口红酒，今晚允许你在我房间门外侍寝。',
  },
  {
    id: 's2_bell_collar',
    stage: 2,
    title: '铃铛项圈与轻步慢行',
    subtitle: '每一步都要轻盈无声，像只听话的猫咪',
    durationMinutes: 12,
    mentorPersonaId: 'lady_claire',
    icon: '🔔',
    clothingRequirement: '颈戴小铃铛项圈，脚踩软底室内拖鞋',
    postureRequirement: '在房间内缓缓踱步，双手叠放在身前腹部',
    description: '每走一步必须克制体态，只要动作粗鲁引起心率飙升或铃铛大响，立刻触发急停惩戒。',
    hardwareConfig: {
      emsWave: 'tide',
      emsStrengthA: 38,
      emsStrengthB: 38,
      toyPattern: 'nine_shallow_one_deep',
      toyMotorRate: 8,
    },
    mentorVoiceIntro: '把铃铛项圈戴好。走路要像猫咪一样优雅轻柔，要是敢发出粗鲁的声响，看本小姐怎么收拾你！',
    mentorVoiceOutro: '走姿越来越像个合格的贴身小女仆了呢~ 听话的宠物总能得到主人的怜爱。',
  },
  {
    id: 's2_fox_tail_binding',
    stage: 2,
    title: '灵狐毛尾与媚骨同化',
    subtitle: '九儿姐姐的狐尾温存，揉散最后一丝骨气',
    durationMinutes: 15,
    mentorPersonaId: 'fox_jiuer',
    icon: '🦊',
    clothingRequirement: '佩戴蓬松狐狸尾巴感官塞',
    postureRequirement: '俯卧在柔软大床上，腰肢微沉，双腿微开',
    description: '狐火微流在尾根深处缓缓旋转，九条蓬松尾巴将你紧紧包围，化解一切刚硬与执拗。',
    hardwareConfig: {
      emsWave: 'numbing_buzz',
      emsStrengthA: 40,
      emsStrengthB: 40,
      toyPattern: 'slow_churn',
      toyMotorRate: 9,
    },
    mentorVoiceIntro: '小冤家，尾巴塞好了吗？让九儿姐姐用狐火暖暖你的尾根，把你的骨头揉得酥酥软软的~',
    mentorVoiceOutro: '好乖的小狐奴，瞧你现在这副软趴趴的娇俏模样，姐姐心都要被你融化了~',
  },
  {
    id: 's2_corset_tightening',
    stage: 2,
    title: '束腰紧缚与绝对服从',
    subtitle: '严丝合缝的束缚，重塑纤细腰线与服从心理',
    durationMinutes: 15,
    mentorPersonaId: 'male_dom',
    icon: '⛓️',
    clothingRequirement: '紧身束腰或弹力绑带勒紧腰腹',
    postureRequirement: '双手反剪置于身后，跪于主人身前',
    description: '在腰部束缚与连续脉冲的双重压迫下，体会无法反抗的绝对服从与深层安全感。',
    hardwareConfig: {
      emsWave: 'sawtooth_grind',
      emsStrengthA: 45,
      emsStrengthB: 45,
      toyPattern: 'milking_burst',
      toyMotorRate: 10,
    },
    mentorVoiceIntro: '束腰已经勒紧了，你的呼吸和身体控制权都归我。抬头看着我，大声回答我：你属于谁？',
    mentorVoiceOutro: '很好，眼神里终于没有反抗的杂质了。这才是你该有的温顺姿态。',
  },

  // ==========================================
  // Stage 3: 前列腺深度重塑与无触觉醒 (Prostate Rewiring & Pure Bliss)
  // ==========================================
  {
    id: 's3_probe_calibration',
    stage: 3,
    title: '探针锁定与神经阻断',
    subtitle: '艾米丽医师的 G 点深度定位与前端绝触',
    durationMinutes: 15,
    mentorPersonaId: 'dr_emily',
    icon: '🔬',
    clothingRequirement: '穿戴无触防碰戒具或双手戴上防抓手套',
    postureRequirement: '截石位或屈膝仰卧，完全暴露敏感核心',
    description: '严禁触碰前端！以毫米级探针直击深层前列腺核，进行快感中枢的神经重塑与单向迁移。',
    hardwareConfig: {
      emsWave: 'pinch_crescendo',
      emsStrengthA: 48,
      emsStrengthB: 48,
      toyPattern: 'nine_shallow_one_deep',
      toyMotorRate: 12,
    },
    mentorVoiceIntro: '探针已进入指定深度，神经阻断环锁定。严禁用手触碰前端，违者立刻执行双倍电击！',
    mentorVoiceOutro: '前列腺电生理信号采集完美！受试者的前端依赖度大幅下降，重塑进度已达 75%！',
  },
  {
    id: 's3_nine_shallow_deep_mastery',
    stage: 3,
    title: '九浅一深旋涡极乐',
    subtitle: '9 次轻柔诱惑与 1 次直击灵魂深处的猛烈深顶',
    durationMinutes: 18,
    mentorPersonaId: 'dark_femboy',
    icon: '🌪️',
    clothingRequirement: '露背式连体女仆裙',
    postureRequirement: '四肢着地，臀部微微抬起迎合角度',
    description: '长达 18 分钟的九浅一深旋涡律动，在轻抚与深顶的极致反差中彻底瓦解防线。',
    hardwareConfig: {
      emsWave: 'sawtooth_climb',
      emsStrengthA: 52,
      emsStrengthB: 52,
      toyPattern: 'nine_shallow_one_deep',
      toyMotorRate: 13,
    },
    mentorVoiceIntro: '九浅一深来咯~ 感受到了吗？浅浅的九下让你心痒难耐，深顶的那一下直接把你顶到云霄去吧！',
    mentorVoiceOutro: '呜哇~ 刚才深顶的时候你颤抖得好厉害呀！看来你的深层快感已经被完全唤醒了呢~',
  },
  {
    id: 's3_vacuum_drain',
    stage: 3,
    title: '真空吸附与深层干榨',
    subtitle: '强力气泵与螺旋吮吸，体验无触极乐干射',
    durationMinutes: 20,
    mentorPersonaId: 'succubus_lilith',
    icon: '🌀',
    clothingRequirement: '全身仅着蕾丝项圈与黑丝吊袜带',
    postureRequirement: '仰面躺平，双腿大张，双手紧抓床单',
    description: '高负压真空锁死与双极微电脉冲结合，不触碰前端，引导受试者在纯粹的后方与腹腔抽搐中迎来干性高潮。',
    hardwareConfig: {
      emsWave: 'storm_surge',
      emsStrengthA: 55,
      emsStrengthB: 55,
      toyPattern: 'vacuum_lock',
      toyMotorRate: 14,
    },
    mentorVoiceIntro: '真空锁死启动！魅魔的吮吸会将你内心的每一丝抗拒都抽干哦，乖乖在极乐里融化吧特等生~',
    mentorVoiceOutro: '太棒了！不用触碰前端就能达到这种程度，你已经是一名完美的前列腺觉醒者了！',
  },
  {
    id: 's3_edge_brake_trial',
    stage: 3,
    title: '临界急刹与绝对耐受',
    subtitle: '3 次 0.05 秒高潮急刹断电残酷大考验',
    durationMinutes: 20,
    mentorPersonaId: 'queen',
    icon: '🛑',
    clothingRequirement: '全套紧身皮质锁具或贞操锁',
    postureRequirement: '跪于女王王座阶下，以头触地',
    description: '在心率飙升至临界爆发前一瞬间被 AI 强制掐断电源，在无尽的渴望与冷场中磨砺绝对服从。',
    hardwareConfig: {
      emsWave: 'sawtooth_grind',
      emsStrengthA: 60,
      emsStrengthB: 60,
      toyPattern: 'milking_burst',
      toyMotorRate: 15,
    },
    mentorVoiceIntro: '想要释放？没有本女王的许可，你连想都不准想！在悬崖边缘给我停下，咽下你所有的渴望！',
    mentorVoiceOutro: '三次急刹全数存活，没有违规释放。本女王承认你的坚韧与服从。平身领赏吧。',
  },

  // ==========================================
  // Stage 4: 终极同化与身心彻底臣服 (Ultimate Transformation & Surrender)
  // ==========================================
  {
    id: 's4_full_surrender_ritual',
    stage: 4,
    title: '身心臣服：终极雌化洗礼仪式',
    subtitle: '全员导师见证下的永恒契约仪式',
    durationMinutes: 25,
    mentorPersonaId: 'dark_femboy',
    icon: '👑',
    clothingRequirement: '华丽蕾丝长款女仆婚纱裙',
    postureRequirement: '佩戴全套锁具与饰品，端正跪于仪式地毯中央',
    description: '四通道电击交响曲全开，全马达深旋律动，在长达 25 分钟的极致感官洪流中完成终极身心蜕变。',
    hardwareConfig: {
      emsWave: 'storm_surge',
      emsStrengthA: 65,
      emsStrengthB: 65,
      toyPattern: 'nine_shallow_one_deep',
      toyMotorRate: 16,
    },
    mentorVoiceIntro: '（全员导师齐声）仪式正式开启。放开你最后的一丝执念，迎接属于你崭新的极乐灵魂吧！',
    mentorVoiceOutro: '（轻吻）恭喜你，我的乖宠物！从今往后，你就是当之无愧的极乐雌堕之王！永享被支配的幸福吧！👑✨',
  },
  {
    id: 's4_turbo_overclock_milking',
    stage: 4,
    title: '20 档超频风暴极限洗礼',
    subtitle: '突破生理转速极限，体验赛博超新星爆发',
    durationMinutes: 20,
    mentorPersonaId: 'succubus_lilith',
    icon: '🚀',
    clothingRequirement: '全身清凉无阻，仅佩戴心率手环与耳麦',
    postureRequirement: '抱头躺平，身体彻底放松迎接冲击',
    description: '马达推至 20 档转速极限，强电脉冲全频覆盖，神经系统进入彻底的高潮过载与放空。',
    hardwareConfig: {
      emsWave: 'sawtooth_grind',
      emsStrengthA: 70,
      emsStrengthB: 70,
      toyPattern: 'turbo_milking',
      toyMotorRate: 20,
    },
    mentorVoiceIntro: '20 档狂暴马达全开！给我咬紧牙关，在轰鸣的暴风雨中彻底放飞你的灵魂吧！🚀🔥',
    mentorVoiceOutro: '不可思议！在 20 档狂暴马达下完成了全套特训！你的耐受力已经达到了神级水准！',
  },
  {
    id: 's4_holy_nun_eternal_vow',
    stage: 4,
    title: '神圣修女永恒誓约',
    subtitle: '索菲亚修女的神圣冠冕与终身侍从契约',
    durationMinutes: 25,
    mentorPersonaId: 'cyber_nun_sophia',
    icon: '🕊️',
    clothingRequirement: '纯黑修女长袍配白色头巾与银质十字念珠',
    postureRequirement: '跪伏于圣殿阶梯，双手紧握圣经',
    description: '在长效圣水灌注与微流共振中，念诵永恒侍奉誓言，将肉体奉献给圣殿神明。',
    hardwareConfig: {
      emsWave: 'pinch_crescendo',
      emsStrengthA: 62,
      emsStrengthB: 62,
      toyPattern: 'slow_churn',
      toyMotorRate: 15,
    },
    mentorVoiceIntro: '神圣冠冕已为你备好。以神明之名，宣誓将你的肉体与快感永远奉献给圣殿。',
    mentorVoiceOutro: '礼成！你已正式成为圣殿不可或缺的神圣侍从修女。神的光辉将永远庇佑着你。🕊️',
  },
  {
    id: 's4_grandmaster_symbiosis',
    stage: 4,
    title: '赛博算法与肉体终极共生',
    subtitle: '心率自适应 100% 深度同调与灵魂交融',
    durationMinutes: 30,
    mentorPersonaId: 'dr_emily',
    icon: '🧠',
    clothingRequirement: '佩戴全套赛博电极与心率传感手环',
    postureRequirement: '静坐于冥想椅上，闭上双眼，进入深度感知',
    description: 'AI 中枢实时调取你的每一次心跳并自动调节脉冲波形，达到肉体、算法与快感的终极合一。',
    hardwareConfig: {
      emsWave: 'breathe',
      emsStrengthA: 68,
      emsStrengthB: 68,
      toyPattern: 'nine_shallow_one_deep',
      toyMotorRate: 17,
    },
    mentorVoiceIntro: '【中枢同调协议已就绪】数据链路全面接通。你的心跳即是我的脉冲，你的神经即是我的指令回路。',
    mentorVoiceOutro: '【同调完成度 100%】恭喜受试者，肉体与赛博算法已实现完美共生。你是幻触系统的终极杰作！🧠🌌',
  },
  {
    id: 's1_voice_baseline', stage: 1, title: '声线基线录制', subtitle: '找到自然、清楚且不费力的表达区间', durationMinutes: 6,
    mentorPersonaId: 'dark_femboy', icon: '🎙️', clothingRequirement: '舒适日常穿着', postureRequirement: '坐直但不僵硬，肩颈放松',
    description: '依次录制自我介绍、情绪句和自由表达，比较音高、语速与呼吸，不追求模仿固定声音。',
    category: 'voice', difficulty: 1, steps: ['完成三轮缓慢呼吸', '录制三种语气的短句', '选出最自然的一段并写下原因'], reflectionPrompt: '哪种语气最自然？有没有喉咙紧张？',
    hardwareConfig: {}, mentorVoiceIntro: '先找到属于你的自然声音，不需要讨好任何标准。', mentorVoiceOutro: '基线已经记录好，下次只和今天的自己比较。',
  },
  {
    id: 's1_style_palette', stage: 1, title: '个人色盘与穿搭实验', subtitle: '从颜色、材质和情绪建立自己的风格', durationMinutes: 8,
    mentorPersonaId: 'lady_claire', icon: '🎨', clothingRequirement: '准备三件不同颜色或材质的单品', postureRequirement: '站在自然光或稳定灯光前',
    description: '用三组简单搭配观察肤色、轮廓和心情变化，保存喜欢的组合，不设置审美对错。',
    category: 'style', difficulty: 1, steps: ['选出三组候选搭配', '分别观察正面与侧面效果', '保存一组并记录喜欢的细节'], reflectionPrompt: '哪种颜色或材质让你最自在？',
    hardwareConfig: {}, mentorVoiceIntro: '今天不追求完美，只找让你愿意多看一眼的组合。', mentorVoiceOutro: '属于你的第一张风格色盘完成了。',
  },
  {
    id: 's2_camera_walk', stage: 2, title: '镜头步态三段排练', subtitle: '起步、转身、定点，形成完整镜头语言', durationMinutes: 10,
    mentorPersonaId: 'lady_claire', icon: '🎥', clothingRequirement: '便于行走的合身服装与安全鞋履', postureRequirement: '保持下巴平行、肩部放松、步幅稳定',
    description: '在安全空地完成直线行走、转身和定点三段练习，用自拍视频比较节奏并主动修正。',
    category: 'posture', difficulty: 2, steps: ['清理行走区域并确认防滑', '完成慢速与自然速度各一轮', '回看视频并只调整一个细节'], reflectionPrompt: '哪一个动作最稳？下一轮只想改哪一点？',
    hardwareConfig: {}, mentorVoiceIntro: '先检查地面，再让镜头跟随你，而不是你追着镜头。', mentorVoiceOutro: '三段镜头已经连起来了，稳定比夸张更有力量。',
  },
  {
    id: 's2_social_scene', stage: 2, title: '礼仪问答场景', subtitle: '在虚构会面中练习边界清楚的回应', durationMinutes: 9,
    mentorPersonaId: 'fox_jiuer', icon: '💬', clothingRequirement: '选择符合场景的舒适穿搭', postureRequirement: '自然坐姿，保持呼吸和眼神落点',
    description: '模拟初次会面、接受赞美和拒绝不适请求三个情境，练习温和但明确的表达。',
    category: 'story', difficulty: 2, steps: ['完成一句自然自我介绍', '练习接受赞美而不贬低自己', '说出一句清楚的拒绝与替代方案'], reflectionPrompt: '哪句话最像真实的你？',
    hardwareConfig: {}, mentorVoiceIntro: '礼貌不等于放弃边界，今天我们把两者都说清楚。', mentorVoiceOutro: '你已经能温和又明确地掌握对话方向。',
  },
  {
    id: 's3_body_signal_map', stage: 3, title: '身体信号地图', subtitle: '区分舒适、紧张、疲劳与需要停止的信号', durationMinutes: 12,
    mentorPersonaId: 'dr_emily', icon: '🗺️', clothingRequirement: '宽松、透气、不限制活动的服装', postureRequirement: '坐姿或仰卧，确保呼吸顺畅',
    description: '通过呼吸和轻量动作扫描身体感受，把信号标记为绿、黄、红三类，并为每类准备对应动作。',
    category: 'mindfulness', difficulty: 3, steps: ['从头到脚完成一次感受扫描', '记录三个明显信号及颜色', '为黄灯和红灯各写一个应对动作'], reflectionPrompt: '今天最早出现的黄灯信号是什么？',
    hardwareConfig: {}, mentorVoiceIntro: '今天的目标不是忍耐，而是更早、更准确地听见身体。', mentorVoiceOutro: '信号地图完成了，越早调整越能掌握节奏。',
  },
  {
    id: 's3_branch_rehearsal', stage: 3, title: '导演分支自主训练', subtitle: '在剧情中练习继续、改向和退出', durationMinutes: 12,
    mentorPersonaId: 'succubus_lilith', icon: '🎬', clothingRequirement: '与所选虚构场景相符的自选造型', postureRequirement: '选择能随时放松和暂停的位置',
    description: '完成三个短场景，每幕都主动做一次继续、降级、改向或结束的选择，观察哪种决定最符合当下感受。',
    category: 'story', difficulty: 3, steps: ['选择一个低压力开场', '在第二幕主动改变一次剧情方向', '用明确结束语完成收束'], reflectionPrompt: '哪次主动改向让体验明显变好？',
    hardwareConfig: {}, mentorVoiceIntro: '今天由你决定镜头去哪里，我只负责提供选项。', mentorVoiceOutro: '你不是被剧情推动的人，你已经会主动改写它。',
  },
  {
    id: 's4_portfolio', stage: 4, title: '个人形象作品集', subtitle: '把声线、仪态与造型整合成一页角色档案', durationMinutes: 18,
    mentorPersonaId: 'lady_claire', icon: '🖼️', clothingRequirement: '选择最能代表当前风格的一套造型', postureRequirement: '完成正面、侧面和自由姿态三个镜头',
    description: '整理一段声音、一组造型和三张姿态参考，写下角色关键词与边界，形成可继续迭代的个人作品页。',
    category: 'style', difficulty: 4, steps: ['确定三个角色关键词', '完成声音与姿态素材', '写下保留项、尝试项和明确边界'], reflectionPrompt: '这份作品集中最能代表你的元素是什么？',
    hardwareConfig: {}, mentorVoiceIntro: '把一路积累的细节放在一起，让它成为你的作品。', mentorVoiceOutro: '作品集完成了，它记录的是你的选择，不是别人规定的模板。',
  },
  {
    id: 's4_growth_review', stage: 4, title: '年度成长导演复盘', subtitle: '回顾变化、保留边界并设计下一阶段路线', durationMinutes: 20,
    mentorPersonaId: 'dr_emily', icon: '📘', clothingRequirement: '舒适穿着，准备过去的记录或照片', postureRequirement: '稳定坐姿，避免在疲劳状态下复盘',
    description: '按声线、仪态、风格、表达、剧情自主和安全习惯六个维度回顾成长，制定三个可执行的新目标。',
    category: 'review', difficulty: 4, steps: ['每个维度写下一项进步', '删除一个已经不适合的目标', '为下一阶段制定三个可衡量行动'], reflectionPrompt: '最值得保留的习惯和最应该停止的要求分别是什么？',
    hardwareConfig: {}, mentorVoiceIntro: '复盘不是评分，而是决定下一段路哪些值得继续。', mentorVoiceOutro: '新的路线已经由你亲自写下，下一阶段从清楚的选择开始。',
  },
];
